      
package com.mentor.nucleus.bp.core ;
//====================================================================
//
// File:      com.mentor.nucleus.bp.core.ReferredToClassInAssoc_c.java
//
// WARNING: Do not edit this generated file
// Generated by ../MC-Java/java.arc, $Revision: 1.111 $
//
// (c) Copyright 2005-2014 by Mentor Graphics Corp.  All rights reserved.
//
//====================================================================

// No special imports
import java.util.* ;
import java.lang.reflect.*;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.runtime.IAdaptable;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;
import com.mentor.nucleus.bp.core.util.PersistenceUtil;
import org.eclipse.core.runtime.NullProgressMonitor;
import com.mentor.nucleus.bp.core.ui.marker.UmlProblem;
import com.mentor.nucleus.bp.core.common.*;      
abstract class EV_REFERRED_TO_CLASS_IN_ASSOC extends genericEvent_c 
{
  public abstract int getEvtcode() ;
}

public class ReferredToClassInAssoc_c extends NonRootModelElement implements IAdaptable, Cloneable
{
  // Public Constructors
  public ReferredToClassInAssoc_c(ModelRoot modelRoot,
       java.util.UUID         p_m_obj_id,
       java.util.UUID         p_m_rel_id,
       java.util.UUID         p_m_oir_id,
       int          p_m_oid_id)
  {
    super(modelRoot);
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       m_oir_id = IdAssigner.preprocessUUID(p_m_oir_id);
       m_oid_id = p_m_oid_id;
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       m_obj_id = IdAssigner.preprocessUUID(p_m_obj_id);
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       m_rel_id = IdAssigner.preprocessUUID(p_m_rel_id);
        
    Object [] key = {m_oir_id,m_obj_id,m_rel_id};
    addInstanceToMap(key);
  }
  static public ReferredToClassInAssoc_c createProxy(ModelRoot modelRoot,
       java.util.UUID         p_m_obj_id,
       java.util.UUID         p_m_rel_id,
       java.util.UUID         p_m_oir_id,
       int          p_m_oid_id, String p_contentPath, IPath p_localPath)
  {
	  ModelRoot resolvedModelRoot = ModelRoot.findModelRoot(modelRoot, p_contentPath, p_localPath);
	  // if a model root was not resolved it is most likely
	  // due to a missing file of the proxy, defualt back to
	  // the original model root
	  if(resolvedModelRoot != null)
	  	modelRoot = resolvedModelRoot;
      InstanceList instances = modelRoot.getInstanceList(ReferredToClassInAssoc_c.class);
      ReferredToClassInAssoc_c new_inst = null;
      synchronized(instances) {
          Object[] key = {p_m_oir_id,p_m_obj_id,p_m_rel_id};
          new_inst = (ReferredToClassInAssoc_c) instances.get(key) ;
        }
	String contentPath = PersistenceUtil.resolveRelativePath(
			p_localPath,
			new Path(p_contentPath));
	if(modelRoot.isNewCompareRoot()) {
	      // for comparisons we do not want to change
	      // the content path
	      contentPath = p_contentPath;
	}
	if ( new_inst != null && !modelRoot.isCompareRoot()) {
		PersistableModelComponent pmc = new_inst.getPersistableComponent();
		if (pmc == null) {
			// dangling reference, redo this instance
			new_inst.batchUnrelate();
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       new_inst.m_oir_id = IdAssigner.preprocessUUID(p_m_oir_id);
       new_inst.m_oid_id = p_m_oid_id;
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       new_inst.m_obj_id = IdAssigner.preprocessUUID(p_m_obj_id);
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       new_inst.m_rel_id = IdAssigner.preprocessUUID(p_m_rel_id);
        
		}
	}
	if ( new_inst == null ) {
		// there is no instance matching the id, create a proxy
		// if the resource doesn't exist then this will be a dangling reference
    	new_inst = new ReferredToClassInAssoc_c(modelRoot,
p_m_obj_id,
p_m_rel_id,
p_m_oir_id,
p_m_oid_id
);
		new_inst.m_contentPath = contentPath;
	}
    return new_inst;
  }

  static public ReferredToClassInAssoc_c resolveInstance(ModelRoot modelRoot,
       java.util.UUID         p_m_obj_id,
       java.util.UUID         p_m_rel_id,
       java.util.UUID         p_m_oir_id,
       int          p_m_oid_id){
    InstanceList instances = modelRoot.getInstanceList(ReferredToClassInAssoc_c.class);
    ReferredToClassInAssoc_c source = null;
    synchronized(instances) {
        Object [] key = {
        p_m_oir_id
        ,
        p_m_obj_id
        ,
        p_m_rel_id
            };
        source = (ReferredToClassInAssoc_c) instances.get(key);
        if (source != null && !modelRoot.isCompareRoot()) {
           source.convertFromProxy();
           source.batchUnrelate();
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       source.m_oir_id = IdAssigner.preprocessUUID(p_m_oir_id);
       source.m_oid_id = p_m_oid_id;
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       source.m_obj_id = IdAssigner.preprocessUUID(p_m_obj_id);
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       source.m_rel_id = IdAssigner.preprocessUUID(p_m_rel_id);
        
           return source ;
        }
      }
      // there is no instance matching the id
    ReferredToClassInAssoc_c new_inst = new ReferredToClassInAssoc_c(modelRoot,
p_m_obj_id,
p_m_rel_id,
p_m_oir_id,
p_m_oid_id
);
    return new_inst;
  }
  public ReferredToClassInAssoc_c(ModelRoot modelRoot)
  {
    super(modelRoot);
     m_oir_id = IdAssigner.NULL_UUID;   
     m_oid_id = -1;   
     m_obj_id = IdAssigner.NULL_UUID;   
     m_rel_id = IdAssigner.NULL_UUID;   
    Object [] key = {m_oir_id,m_obj_id,m_rel_id};
    addInstanceToMap(key);
  }

  public Object getInstanceKey() {
    Object [] key =  {m_oir_id,m_obj_id,m_rel_id};
		return key;
  }
  
  public boolean setInstanceKey(UUID p_newKey){
  
  	boolean changed = false;
		// round p1
		// round p2
		// round p3
			// round p4
			// round p5
	if (m_oir_id !=  p_newKey ){
	
		m_oir_id = p_newKey; 	
		changed = true;
	}
  	return changed;
  }
  

  



  public boolean equals (Object elem) {
     if (!(elem instanceof ReferredToClassInAssoc_c)) {
         return false;
     }
	    // check that the model-roots are the same
    	if (((NonRootModelElement)elem).getModelRoot() != getModelRoot() && !getModelRoot().isCompareRoot()) {
    		return false;
    	}
    	
     return identityEquals(elem);
  }
  
   public boolean identityEquals(Object elem) {
       if (!(elem instanceof ReferredToClassInAssoc_c)) {
           return false;
       }
       
       ReferredToClassInAssoc_c me = (ReferredToClassInAssoc_c)elem;
      // don't allow an empty id-value to produce a false positive result;
      // in this case, use whether the two instances are actually the same 
      // one in memory, instead
      if (!getModelRoot().isCompareRoot() && ((IdAssigner.NULL_UUID.equals(getOir_id()) || IdAssigner.NULL_UUID.equals(((ReferredToClassInAssoc_c)elem).getOir_id())) && this != elem)) {
      	return false;
      }
      if (!getOir_id().equals(((ReferredToClassInAssoc_c)elem).getOir_id())) return false;
      // don't allow an empty id-value to produce a false positive result;
      // in this case, use whether the two instances are actually the same 
      // one in memory, instead
      if (!getModelRoot().isCompareRoot() && ((IdAssigner.NULL_UUID.equals(getObj_id()) || IdAssigner.NULL_UUID.equals(((ReferredToClassInAssoc_c)elem).getObj_id())) && this != elem)) {
      	return false;
      }
      if (!getObj_id().equals(((ReferredToClassInAssoc_c)elem).getObj_id())) return false;
      // don't allow an empty id-value to produce a false positive result;
      // in this case, use whether the two instances are actually the same 
      // one in memory, instead
      if (!getModelRoot().isCompareRoot() && ((IdAssigner.NULL_UUID.equals(getRel_id()) || IdAssigner.NULL_UUID.equals(((ReferredToClassInAssoc_c)elem).getRel_id())) && this != elem)) {
      	return false;
      }
      if (!getRel_id().equals(((ReferredToClassInAssoc_c)elem).getRel_id())) return false;
      return true;
    }

   public boolean cachedIdentityEquals(Object elem) {
       if (!(elem instanceof ReferredToClassInAssoc_c)) {
           return false;
       }
       
       ReferredToClassInAssoc_c me = (ReferredToClassInAssoc_c)elem;
      if (!getOir_idCachedValue().equals(((ReferredToClassInAssoc_c)elem).getOir_idCachedValue())) return false;
      if (!getObj_idCachedValue().equals(((ReferredToClassInAssoc_c)elem).getObj_idCachedValue())) return false;
      if (!getRel_idCachedValue().equals(((ReferredToClassInAssoc_c)elem).getRel_idCachedValue())) return false;
      return true;
    }


  // Attributes
  private java.util.UUID         m_oir_id ;
  private int          m_oid_id ;
  private java.util.UUID         m_obj_id ;
  private java.util.UUID         m_rel_id ;
      
// declare association references from this class
  
  
    
// referring navigation

ClassInAssociation_c IsSupertypeClassInAssociation ;
public void relateAcrossR203To(ClassInAssociation_c target)
{
	relateAcrossR203To(target, true);
}
public void relateAcrossR203To(ClassInAssociation_c target, boolean notifyChanges)
{
	if (target == null) return;
	
	if (target == IsSupertypeClassInAssociation) return;  // already related

    if ( IsSupertypeClassInAssociation != target ) {
    
    Object oldKey = getInstanceKey();

    if (IsSupertypeClassInAssociation != null) {
    
        IsSupertypeClassInAssociation.clearBackPointerR203To(this);
        
		if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == true) {   //$NON-NLS-1$
		Ooaofooa.log.println(ILogger.CONSISTENCY, 
			"ReferredToClassInAssoc_c.relateAcrossR203To(ClassInAssociation_c target)", 
			"Relate performed across R203 from Referred To Class in Assoc to Class In Association without unrelate of prior instance.");  
		}
    }
                
    	IsSupertypeClassInAssociation = target ;
        m_oir_id = target.getOir_id();
        if(IdAssigner.NULL_UUID.equals(target.getObj_id()))
        {
            // do not update cached value
        } else {
          // update cached value
          m_obj_id = target.getObj_idCachedValue();
        }
        if(IdAssigner.NULL_UUID.equals(target.getRel_id()))
        {
            // do not update cached value
        } else {
          // update cached value
          m_rel_id = target.getRel_idCachedValue();
        }
      updateInstanceKey(oldKey, getInstanceKey());
	    target.setBackPointerR203To(this);
        target.addRef();
      if(notifyChanges) {
	    	RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(Modeleventnotification_c.DELTA_ELEMENT_RELATED, this, target, "203", "");
        Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(change);
      }
    }
}
public void unrelateAcrossR203From(ClassInAssociation_c target)
{
	unrelateAcrossR203From(target, true);
}
public void unrelateAcrossR203From(ClassInAssociation_c target, boolean notifyChanges)
{
	if (target == null) return;
	
	if (IsSupertypeClassInAssociation == null) return;  // already unrelated
	
	if (target != IsSupertypeClassInAssociation) {
		Exception e = new Exception();
		e.fillInStackTrace();
		CorePlugin.logError("Tried to unrelate from non-related instance across R203", e);
		return;
	}

    if (target != null) {
        target.clearBackPointerR203To(this);
    }
    

      if(IsSupertypeClassInAssociation != null) {
      
        m_oir_id = IsSupertypeClassInAssociation.getOir_id();
        m_obj_id = IsSupertypeClassInAssociation.getObj_id();
        if(IdAssigner.NULL_UUID.equals(m_obj_id))
        {
          m_obj_id = IsSupertypeClassInAssociation.getObj_idCachedValue();
        }       
        m_rel_id = IsSupertypeClassInAssociation.getRel_id();
        if(IdAssigner.NULL_UUID.equals(m_rel_id))
        {
          m_rel_id = IsSupertypeClassInAssociation.getRel_idCachedValue();
        }       
        IsSupertypeClassInAssociation = null ;
        target.removeRef();
      if(notifyChanges) { 
        RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(Modeleventnotification_c.DELTA_ELEMENT_UNRELATED, this, target, "203", "");
        Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(change);
      }
    }
}

  
    
      
public static ReferredToClassInAssoc_c getOneR_RTOOnR203(ClassInAssociation_c [] targets)
{
    return getOneR_RTOOnR203(targets, null);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR203(ClassInAssociation_c [] targets, ClassQueryInterface_c test)
{
    ReferredToClassInAssoc_c ret_val = null;
    if (targets != null)
    {
        for (int i = 0; i < targets.length && ret_val == null; ++i )
        {
           ret_val = getOneR_RTOOnR203(targets[i], test);
        }
    }

    return ret_val;
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR203(ClassInAssociation_c target)
{
  return getOneR_RTOOnR203(target, null);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR203(ClassInAssociation_c target, boolean loadComponent)
{
    return getOneR_RTOOnR203(target.getModelRoot(), target, null, loadComponent);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR203(ClassInAssociation_c target, ClassQueryInterface_c test)
{
  if (target != null) {
    return getOneR_RTOOnR203(target.getModelRoot(), target, test);
  }
  return null;
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR203(ModelRoot modelRoot, ClassInAssociation_c target, ClassQueryInterface_c test)
{
	return getOneR_RTOOnR203(modelRoot, target, test, true);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR203(ModelRoot modelRoot, ClassInAssociation_c target, ClassQueryInterface_c test, boolean loadComponent)
{
   return find_getOneR_RTOOnR203(modelRoot,target,test);
}
private static ReferredToClassInAssoc_c find_getOneR_RTOOnR203(ModelRoot modelRoot, ClassInAssociation_c target, ClassQueryInterface_c test)
{
  if (target != null) {
    ReferredToClassInAssoc_c source = (ReferredToClassInAssoc_c)target.backPointer_IsSubtypeReferredToClassInAssocIsSubtype_R203;
    if (source != null && (test == null || test.evaluate(source))) {
      return source;
    }
  }
  // not found
  return null ;
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR203(ClassInAssociation_c [] targets)
{
  return getManyR_RTOsOnR203(targets, null);
}
public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR203(ClassInAssociation_c [] targets, boolean loadComponent)
{
  return getManyR_RTOsOnR203(targets, null, loadComponent);
}
public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR203(ClassInAssociation_c [] targets, ClassQueryInterface_c test)
{
	return getManyR_RTOsOnR203(targets, test, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR203(ClassInAssociation_c [] targets, ClassQueryInterface_c test, boolean loadComponent)
{

  if(targets == null || targets.length == 0 || targets[0] == null)
  	return new ReferredToClassInAssoc_c[0];

  ModelRoot modelRoot = targets[0].getModelRoot();
 
   InstanceList instances = modelRoot.getInstanceList(ReferredToClassInAssoc_c.class);

  Vector matches = new Vector();
  for (int i = 0 ; i < targets.length ; i++) {
      ReferredToClassInAssoc_c source = (ReferredToClassInAssoc_c)targets[i].backPointer_IsSubtypeReferredToClassInAssocIsSubtype_R203;
      if (source != null && (test == null || test.evaluate(source))) {
        matches.add(source);
      }
  }
  if (matches.size() > 0) {
	ReferredToClassInAssoc_c[] ret_set = new ReferredToClassInAssoc_c[matches.size()];
	matches.copyInto(ret_set);
	return ret_set;
  } else {
	return new ReferredToClassInAssoc_c[0];
  }
  }

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR203(ClassInAssociation_c target)
{
  if (target != null) {
    ClassInAssociation_c [] targetArray = new ClassInAssociation_c[1];
    targetArray[0] = target;
    return getManyR_RTOsOnR203(targetArray);
  } else {
    ReferredToClassInAssoc_c [] result = new ReferredToClassInAssoc_c [0] ;
  return result ;
}
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR203(ClassInAssociation_c target, boolean loadComponent)
{
  if (target != null) {
    ClassInAssociation_c [] targetArray = new ClassInAssociation_c[1];
    targetArray[0] = target;
    return getManyR_RTOsOnR203(targetArray, loadComponent);
  } else {
    ReferredToClassInAssoc_c [] result = new ReferredToClassInAssoc_c [0] ;
  return result ;
}
}



  
    
// referring navigation

ClassIdentifier_c IsIdentifiedInThisAssociationByClassIdentifier ;
public void relateAcrossR109To(ClassIdentifier_c target)
{
	relateAcrossR109To(target, true);
}
public void relateAcrossR109To(ClassIdentifier_c target, boolean notifyChanges)
{
	if (target == null) return;
	
	if (target == IsIdentifiedInThisAssociationByClassIdentifier) return;  // already related

    if ( IsIdentifiedInThisAssociationByClassIdentifier != target ) {
    
    Object oldKey = getInstanceKey();

    if (IsIdentifiedInThisAssociationByClassIdentifier != null) {
        UmlProblem.removeXtUMLProblem(this, IsIdentifiedInThisAssociationByClassIdentifier);
    
        IsIdentifiedInThisAssociationByClassIdentifier.clearBackPointerR109To(this);
        
		if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == true) {   //$NON-NLS-1$
		Ooaofooa.log.println(ILogger.CONSISTENCY, 
			"ReferredToClassInAssoc_c.relateAcrossR109To(ClassIdentifier_c target)", 
			"Relate performed across R109 from Referred To Class in Assoc to Class Identifier without unrelate of prior instance.");  
		}
    }
                
    	IsIdentifiedInThisAssociationByClassIdentifier = target ;
        if(IdAssigner.NULL_UUID.equals(target.getObj_id()))
        {
            // do not update cached value
        } else {
          // update cached value
          m_obj_id = target.getObj_idCachedValue();
        }
        m_oid_id = target.getOid_id();
      updateInstanceKey(oldKey, getInstanceKey());
	    target.setBackPointerR109To(this);
        target.addRef();
        UmlProblem.handleDanglingReference(this, target);
      if(notifyChanges) {
	    	RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(Modeleventnotification_c.DELTA_ELEMENT_RELATED, this, target, "109", "");
        Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(change);
      }
    }
}
public void unrelateAcrossR109From(ClassIdentifier_c target)
{
	unrelateAcrossR109From(target, true);
}
public void unrelateAcrossR109From(ClassIdentifier_c target, boolean notifyChanges)
{
	if (target == null) return;
	
	if (IsIdentifiedInThisAssociationByClassIdentifier == null) return;  // already unrelated
	
	if (target != IsIdentifiedInThisAssociationByClassIdentifier) {
		Exception e = new Exception();
		e.fillInStackTrace();
		CorePlugin.logError("Tried to unrelate from non-related instance across R109", e);
		return;
	}

    if (target != null) {
        target.clearBackPointerR109To(this);
    }
    

      if(IsIdentifiedInThisAssociationByClassIdentifier != null) {
      
        m_obj_id = IsIdentifiedInThisAssociationByClassIdentifier.getObj_id();
        if(IdAssigner.NULL_UUID.equals(m_obj_id))
        {
          m_obj_id = IsIdentifiedInThisAssociationByClassIdentifier.getObj_idCachedValue();
        }       
        m_oid_id = IsIdentifiedInThisAssociationByClassIdentifier.getOid_id();
        IsIdentifiedInThisAssociationByClassIdentifier = null ;
        target.removeRef();
        UmlProblem.removeXtUMLProblem(this, target);
      if(notifyChanges) { 
        RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(Modeleventnotification_c.DELTA_ELEMENT_UNRELATED, this, target, "109", "");
        Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(change);
      }
    }
}

  
    
      
public static ReferredToClassInAssoc_c getOneR_RTOOnR109(ClassIdentifier_c [] targets)
{
    return getOneR_RTOOnR109(targets, null);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR109(ClassIdentifier_c [] targets, ClassQueryInterface_c test)
{
    ReferredToClassInAssoc_c ret_val = null;
    if (targets != null)
    {
        for (int i = 0; i < targets.length && ret_val == null; ++i )
        {
           ret_val = getOneR_RTOOnR109(targets[i], test);
        }
    }

    return ret_val;
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR109(ClassIdentifier_c target)
{
  return getOneR_RTOOnR109(target, null);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR109(ClassIdentifier_c target, boolean loadComponent)
{
    return getOneR_RTOOnR109(target.getModelRoot(), target, null, loadComponent);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR109(ClassIdentifier_c target, ClassQueryInterface_c test)
{
  if (target != null) {
    return getOneR_RTOOnR109(target.getModelRoot(), target, test);
  }
  return null;
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR109(ModelRoot modelRoot, ClassIdentifier_c target, ClassQueryInterface_c test)
{
	return getOneR_RTOOnR109(modelRoot, target, test, true);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR109(ModelRoot modelRoot, ClassIdentifier_c target, ClassQueryInterface_c test, boolean loadComponent)
{
  ReferredToClassInAssoc_c result = null;
  
  result=find_getOneR_RTOOnR109(modelRoot,target,test);
  if (result==null && (loadComponent)) {
     // not a Containment Relation
     List comps =  PersistenceManager.findAllComponents(modelRoot,ReferredToClassInAssoc_c.class);
    for (int i = 0; i < comps.size(); i++) {
      PersistableModelComponent component = (PersistableModelComponent) comps.get(i);
      if (!component.isLoaded()) {
        try {
          component.load(new NullProgressMonitor());
          result=find_getOneR_RTOOnR109(modelRoot,target,test);
          if(result!=null) return result;
        } catch (Exception e) {
          CorePlugin.logError("Error Loading component", e);
        }
      }
    }
  }
  
  return result;
}
private static ReferredToClassInAssoc_c find_getOneR_RTOOnR109(ModelRoot modelRoot, ClassIdentifier_c target, ClassQueryInterface_c test)
{
  if (target != null) {
    synchronized(target.backPointer_IdentifiesForThisAssociationReferredToClassInAssocIdentifiesForThisAssociation_R109) {
	    for ( int i = 0; i < target.backPointer_IdentifiesForThisAssociationReferredToClassInAssocIdentifiesForThisAssociation_R109.size(); ++i ) {
	      ReferredToClassInAssoc_c source = (ReferredToClassInAssoc_c)target.backPointer_IdentifiesForThisAssociationReferredToClassInAssocIdentifiesForThisAssociation_R109.get(i) ;
	      if (source != null && (test == null || test.evaluate(source))) {
	        return source ;
      }
    }
  }
  }
  // not found
  return null ;
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR109(ClassIdentifier_c [] targets)
{
  return getManyR_RTOsOnR109(targets, null);
}
public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR109(ClassIdentifier_c [] targets, boolean loadComponent)
{
  return getManyR_RTOsOnR109(targets, null, loadComponent);
}
public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR109(ClassIdentifier_c [] targets, ClassQueryInterface_c test)
{
	return getManyR_RTOsOnR109(targets, test, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR109(ClassIdentifier_c [] targets, ClassQueryInterface_c test, boolean loadComponent)
{

  if(targets == null || targets.length == 0 || targets[0] == null)
  	return new ReferredToClassInAssoc_c[0];

  ModelRoot modelRoot = targets[0].getModelRoot();
  if(loadComponent){
     //not a Containment Relation
	 PersistenceManager.ensureAllInstancesLoaded(modelRoot, ReferredToClassInAssoc_c.class);
  
  }
 
   InstanceList instances = modelRoot.getInstanceList(ReferredToClassInAssoc_c.class);

  Vector matches = new Vector();
  for (int i = 0 ; i < targets.length ; i++) {
    synchronized(targets[i].backPointer_IdentifiesForThisAssociationReferredToClassInAssocIdentifiesForThisAssociation_R109) {
	    for (int j = 0; j < targets[i].backPointer_IdentifiesForThisAssociationReferredToClassInAssocIdentifiesForThisAssociation_R109.size(); ++j) {
	      ReferredToClassInAssoc_c source = (ReferredToClassInAssoc_c)targets[i].backPointer_IdentifiesForThisAssociationReferredToClassInAssocIdentifiesForThisAssociation_R109.get(j) ;
          if (source != null && (test == null || test.evaluate(source))) {
	        matches.add(source);
    }
  }
    }
  }
  if (matches.size() > 0) {
	ReferredToClassInAssoc_c[] ret_set = new ReferredToClassInAssoc_c[matches.size()];
	matches.copyInto(ret_set);
	return ret_set;
  } else {
	return new ReferredToClassInAssoc_c[0];
  }
  }

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR109(ClassIdentifier_c target)
{
  return getManyR_RTOsOnR109(target, null);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR109(ClassIdentifier_c target, boolean loadComponent)
{
  return getManyR_RTOsOnR109(target, null, loadComponent);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR109(ClassIdentifier_c target, ClassQueryInterface_c test)
{
	return getManyR_RTOsOnR109(target, test, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR109(ClassIdentifier_c target, ClassQueryInterface_c test, boolean loadComponent)
{
  if(target == null)
    return new ReferredToClassInAssoc_c[0];    

  ModelRoot modelRoot = target.getModelRoot();
  if(loadComponent){
     //not a Containment Relation
	 PersistenceManager.ensureAllInstancesLoaded(modelRoot, ReferredToClassInAssoc_c.class);
  }
  Vector matches = new Vector();
  synchronized(target.backPointer_IdentifiesForThisAssociationReferredToClassInAssocIdentifiesForThisAssociation_R109) {
    for (int i = 0; i < target.backPointer_IdentifiesForThisAssociationReferredToClassInAssocIdentifiesForThisAssociation_R109.size(); ++i) {
      ReferredToClassInAssoc_c source = (ReferredToClassInAssoc_c)target.backPointer_IdentifiesForThisAssociationReferredToClassInAssocIdentifiesForThisAssociation_R109.get(i);
      if (source != null && (test == null || test.evaluate(source))) {

        matches.add(source);
	  }
	}
  }
  
	if (matches.size() > 0) {
		ReferredToClassInAssoc_c[] ret_set = new ReferredToClassInAssoc_c[matches.size()];
		matches.copyInto(ret_set);
		return ret_set;
	} else {
		return new ReferredToClassInAssoc_c[0];
	}
  }



// declare associations referring to this class

    
  
  
// referred to navigation

ArrayList<ReferredToIdentifierAttribute_c> backPointer_IsIdentifiedInThisAssociationByReferredToIdentifierAttributeIsIdentifiedInThisAssociationBy_R110 = new ArrayList<ReferredToIdentifierAttribute_c>();

public void setReferredToIdentifierAttributeOrderInChildListR110(ReferredToIdentifierAttribute_c target, int index) {
	unrelateAcrossR110From(target);
	ReferredToIdentifierAttribute_c[] elements = ReferredToIdentifierAttribute_c.getManyO_RTIDAsOnR110(this);
	int count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			unrelateAcrossR110From((ReferredToIdentifierAttribute_c) elements[i]); 
		}
		count++;
	}
	relateAcrossR110To(target);
	count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			relateAcrossR110To((ReferredToIdentifierAttribute_c) elements[i]);
		}
		count++;
	}
}

public void relateAcrossR110To(ReferredToIdentifierAttribute_c target)
{
  if (target != null) {
    target.relateAcrossR110To(this, true) ;
  }
}

public void relateAcrossR110To(ReferredToIdentifierAttribute_c target, boolean notifyChanges)
{
  if (target != null) {
    target.relateAcrossR110To(this, notifyChanges) ;
  }
}

public void setBackPointerR110To(ReferredToIdentifierAttribute_c target)
{
  	synchronized (backPointer_IsIdentifiedInThisAssociationByReferredToIdentifierAttributeIsIdentifiedInThisAssociationBy_R110) {
		backPointer_IsIdentifiedInThisAssociationByReferredToIdentifierAttributeIsIdentifiedInThisAssociationBy_R110.add(target);
	}
}

public void unrelateAcrossR110From(ReferredToIdentifierAttribute_c target)
{
  if (target != null) {
    target.unrelateAcrossR110From(this, true) ;
  }
}

public void unrelateAcrossR110From(ReferredToIdentifierAttribute_c target, boolean notifyChanges)
{
  if (target != null) {
    target.unrelateAcrossR110From(this, notifyChanges) ;
  }
}

public void clearBackPointerR110To(ReferredToIdentifierAttribute_c target)
{
  synchronized (backPointer_IsIdentifiedInThisAssociationByReferredToIdentifierAttributeIsIdentifiedInThisAssociationBy_R110) {
	    backPointer_IsIdentifiedInThisAssociationByReferredToIdentifierAttributeIsIdentifiedInThisAssociationBy_R110.remove(target);
	}
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR110(ReferredToIdentifierAttribute_c [] targets)
{
    return getOneR_RTOOnR110(targets, null);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR110(ReferredToIdentifierAttribute_c [] targets, ClassQueryInterface_c test)
{
    return getOneR_RTOOnR110(targets, test, true);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR110(ReferredToIdentifierAttribute_c [] targets, ClassQueryInterface_c test, boolean loadComponent)
{
    ReferredToClassInAssoc_c ret_val = null;
    if (targets != null)
    {
        for (int i = 0; i < targets.length && ret_val == null; ++i )
        {
           if (test != null) {
             ReferredToClassInAssoc_c candidate_val = getOneR_RTOOnR110(targets[i],true);
             if ( candidate_val != null && test.evaluate(candidate_val) )
             {
               ret_val = candidate_val;
               break;
             }
           }
           else {
             ret_val = getOneR_RTOOnR110(targets[i], loadComponent);
             if (ret_val != null) {
               break;
             }
           }
        }
    }
    return ret_val;
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR110(ReferredToIdentifierAttribute_c target)
{
	return getOneR_RTOOnR110(target, true);
}
public static ReferredToClassInAssoc_c getOneR_RTOOnR110(ReferredToIdentifierAttribute_c target, boolean loadComponent)
{
  if (target != null) {
	if(loadComponent){
	     target.loadProxy();
	    if(target.IdentifiesForThisAssociationReferredToClassInAssoc != null){
		target.IdentifiesForThisAssociationReferredToClassInAssoc.loadProxy();
	}
	}
    return target.IdentifiesForThisAssociationReferredToClassInAssoc ;
  } else {
    return null;
  }
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ReferredToIdentifierAttribute_c [] targets,
    ClassQueryInterface_c test)
{
	return getManyR_RTOsOnR110(targets, test, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ReferredToIdentifierAttribute_c [] targets,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if(targets == null || targets.length == 0 || targets[0] == null)
    return new ReferredToClassInAssoc_c[0];
  
  
  LinkedHashSet<ReferredToClassInAssoc_c> elementsSet = new LinkedHashSet<ReferredToClassInAssoc_c>();
  for (int i = 0; i < targets.length; i++) {
	if(loadComponent && targets[i] != null && targets[i].IdentifiesForThisAssociationReferredToClassInAssoc == null)
	  targets[i].loadProxy();
    ReferredToClassInAssoc_c associate = targets[i].IdentifiesForThisAssociationReferredToClassInAssoc;
    if (targets[i] != null && associate != null
    	&& (test == null || test.evaluate(associate))) {
        	if (elementsSet.add(associate)){ 
                if(loadComponent){
                   associate.loadProxy();
                }
            }
    }
  }

  ReferredToClassInAssoc_c[] result = new ReferredToClassInAssoc_c[elementsSet.size()];
  elementsSet.toArray(result);
  return result;
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ReferredToIdentifierAttribute_c [] targets)
{
  return getManyR_RTOsOnR110(targets, null);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ReferredToIdentifierAttribute_c target,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if (target != null) {
    ReferredToIdentifierAttribute_c [] targetArray = new ReferredToIdentifierAttribute_c[1];
    targetArray[0] = target;
    return getManyR_RTOsOnR110(targetArray, test, loadComponent);
  } else {
    ReferredToClassInAssoc_c [] result = new ReferredToClassInAssoc_c [0] ;
    return result ;
  }
  
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ReferredToIdentifierAttribute_c target,
    ClassQueryInterface_c test)
{
    return getManyR_RTOsOnR110(target, null, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ReferredToIdentifierAttribute_c target)
{
    return getManyR_RTOsOnR110(target, null, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ReferredToIdentifierAttribute_c target, boolean loadComponent)
{
    return getManyR_RTOsOnR110(target, null, loadComponent);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR110(ClassIdentifierAttribute_c target)
{
  return ReferredToClassInAssoc_c.getOneR_RTOOnR110(ReferredToIdentifierAttribute_c.getOneO_RTIDAOnR110(target)) ;
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR110(ClassIdentifierAttribute_c target,
    ClassQueryInterface_c test)
{
  return ReferredToClassInAssoc_c.getOneR_RTOOnR110(ReferredToIdentifierAttribute_c.getManyO_RTIDAsOnR110(target), test) ;
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ClassIdentifierAttribute_c target,
    ClassQueryInterface_c test)
{
	return getManyR_RTOsOnR110(target, test, true);
}
public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ClassIdentifierAttribute_c target,
    ClassQueryInterface_c test, boolean loadComponent)
{

  ReferredToIdentifierAttribute_c [] associators = ReferredToIdentifierAttribute_c.getManyO_RTIDAsOnR110(target, loadComponent) ;
    return ReferredToClassInAssoc_c.getManyR_RTOsOnR110(associators, test, loadComponent) ;
}
public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ClassIdentifierAttribute_c target)
{
    return getManyR_RTOsOnR110(target, null, true);
}
public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR110(ClassIdentifierAttribute_c target, boolean loadComponent)
{
    return getManyR_RTOsOnR110(target, null, loadComponent);
}


    
  
  
// referred to navigation

ClassAsSupertype_c backPointer_IsSubtypeClassAsSupertypeIsSubtype_R204;

public void setClassAsSupertypeOrderInChildListR204(ClassAsSupertype_c target, int index) {
	unrelateAcrossR204From(target);
	ClassAsSupertype_c[] elements = ClassAsSupertype_c.getManyR_SUPERsOnR204(this);
	int count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			unrelateAcrossR204From((ClassAsSupertype_c) elements[i]); 
		}
		count++;
	}
	relateAcrossR204To(target);
	count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			relateAcrossR204To((ClassAsSupertype_c) elements[i]);
		}
		count++;
	}
}

public void relateAcrossR204To(ClassAsSupertype_c target)
{
  if (target != null) {
    target.relateAcrossR204To(this, true) ;
  }
}

public void relateAcrossR204To(ClassAsSupertype_c target, boolean notifyChanges)
{
  if (target != null) {
    target.relateAcrossR204To(this, notifyChanges) ;
  }
}

public void setBackPointerR204To(ClassAsSupertype_c target)
{
    backPointer_IsSubtypeClassAsSupertypeIsSubtype_R204 = target;
}

public void unrelateAcrossR204From(ClassAsSupertype_c target)
{
  if (target != null) {
    target.unrelateAcrossR204From(this, true) ;
  }
}

public void unrelateAcrossR204From(ClassAsSupertype_c target, boolean notifyChanges)
{
  if (target != null) {
    target.unrelateAcrossR204From(this, notifyChanges) ;
  }
}

public void clearBackPointerR204To(ClassAsSupertype_c target)
{
	if (target == backPointer_IsSubtypeClassAsSupertypeIsSubtype_R204) {
		backPointer_IsSubtypeClassAsSupertypeIsSubtype_R204 = null;
	}
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsSupertype_c [] targets)
{
    return getOneR_RTOOnR204(targets, null);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsSupertype_c [] targets, ClassQueryInterface_c test)
{
    return getOneR_RTOOnR204(targets, test, true);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsSupertype_c [] targets, ClassQueryInterface_c test, boolean loadComponent)
{
    ReferredToClassInAssoc_c ret_val = null;
    if (targets != null)
    {
        for (int i = 0; i < targets.length && ret_val == null; ++i )
        {
           if (test != null) {
             ReferredToClassInAssoc_c candidate_val = getOneR_RTOOnR204(targets[i],true);
             if ( candidate_val != null && test.evaluate(candidate_val) )
             {
               ret_val = candidate_val;
               break;
             }
           }
           else {
             ret_val = getOneR_RTOOnR204(targets[i], loadComponent);
             if (ret_val != null) {
               break;
             }
           }
        }
    }
    return ret_val;
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsSupertype_c target)
{
	return getOneR_RTOOnR204(target, true);
}
public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsSupertype_c target, boolean loadComponent)
{
  if (target != null) {
	if(loadComponent){
	     target.loadProxy();
	}
    return target.IsSupertypeReferredToClassInAssoc ;
  } else {
    return null;
  }
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSupertype_c [] targets,
    ClassQueryInterface_c test)
{
	return getManyR_RTOsOnR204(targets, test, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSupertype_c [] targets,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if(targets == null || targets.length == 0 || targets[0] == null)
    return new ReferredToClassInAssoc_c[0];
  
  
  LinkedHashSet<ReferredToClassInAssoc_c> elementsSet = new LinkedHashSet<ReferredToClassInAssoc_c>();
  for (int i = 0; i < targets.length; i++) {
	if(loadComponent && targets[i] != null && targets[i].IsSupertypeReferredToClassInAssoc == null)
	  targets[i].loadProxy();
    ReferredToClassInAssoc_c associate = targets[i].IsSupertypeReferredToClassInAssoc;
    if (targets[i] != null && associate != null
    	&& (test == null || test.evaluate(associate))) {
        	if (elementsSet.add(associate)){ 
            }
    }
  }

  ReferredToClassInAssoc_c[] result = new ReferredToClassInAssoc_c[elementsSet.size()];
  elementsSet.toArray(result);
  return result;
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSupertype_c [] targets)
{
  return getManyR_RTOsOnR204(targets, null);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSupertype_c target,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if (target != null) {
    ClassAsSupertype_c [] targetArray = new ClassAsSupertype_c[1];
    targetArray[0] = target;
    return getManyR_RTOsOnR204(targetArray, test, loadComponent);
  } else {
    ReferredToClassInAssoc_c [] result = new ReferredToClassInAssoc_c [0] ;
    return result ;
  }
  
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSupertype_c target,
    ClassQueryInterface_c test)
{
    return getManyR_RTOsOnR204(target, null, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSupertype_c target)
{
    return getManyR_RTOsOnR204(target, null, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSupertype_c target, boolean loadComponent)
{
    return getManyR_RTOsOnR204(target, null, loadComponent);
}

  
  
  
// referred to navigation

ClassAsSimpleParticipant_c backPointer_IsSubtypeClassAsSimpleParticipantIsSubtype_R204;

public void setClassAsSimpleParticipantOrderInChildListR204(ClassAsSimpleParticipant_c target, int index) {
	unrelateAcrossR204From(target);
	ClassAsSimpleParticipant_c[] elements = ClassAsSimpleParticipant_c.getManyR_PARTsOnR204(this);
	int count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			unrelateAcrossR204From((ClassAsSimpleParticipant_c) elements[i]); 
		}
		count++;
	}
	relateAcrossR204To(target);
	count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			relateAcrossR204To((ClassAsSimpleParticipant_c) elements[i]);
		}
		count++;
	}
}

public void relateAcrossR204To(ClassAsSimpleParticipant_c target)
{
  if (target != null) {
    target.relateAcrossR204To(this, true) ;
  }
}

public void relateAcrossR204To(ClassAsSimpleParticipant_c target, boolean notifyChanges)
{
  if (target != null) {
    target.relateAcrossR204To(this, notifyChanges) ;
  }
}

public void setBackPointerR204To(ClassAsSimpleParticipant_c target)
{
    backPointer_IsSubtypeClassAsSimpleParticipantIsSubtype_R204 = target;
}

public void unrelateAcrossR204From(ClassAsSimpleParticipant_c target)
{
  if (target != null) {
    target.unrelateAcrossR204From(this, true) ;
  }
}

public void unrelateAcrossR204From(ClassAsSimpleParticipant_c target, boolean notifyChanges)
{
  if (target != null) {
    target.unrelateAcrossR204From(this, notifyChanges) ;
  }
}

public void clearBackPointerR204To(ClassAsSimpleParticipant_c target)
{
	if (target == backPointer_IsSubtypeClassAsSimpleParticipantIsSubtype_R204) {
		backPointer_IsSubtypeClassAsSimpleParticipantIsSubtype_R204 = null;
	}
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsSimpleParticipant_c [] targets)
{
    return getOneR_RTOOnR204(targets, null);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsSimpleParticipant_c [] targets, ClassQueryInterface_c test)
{
    return getOneR_RTOOnR204(targets, test, true);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsSimpleParticipant_c [] targets, ClassQueryInterface_c test, boolean loadComponent)
{
    ReferredToClassInAssoc_c ret_val = null;
    if (targets != null)
    {
        for (int i = 0; i < targets.length && ret_val == null; ++i )
        {
           if (test != null) {
             ReferredToClassInAssoc_c candidate_val = getOneR_RTOOnR204(targets[i],true);
             if ( candidate_val != null && test.evaluate(candidate_val) )
             {
               ret_val = candidate_val;
               break;
             }
           }
           else {
             ret_val = getOneR_RTOOnR204(targets[i], loadComponent);
             if (ret_val != null) {
               break;
             }
           }
        }
    }
    return ret_val;
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsSimpleParticipant_c target)
{
	return getOneR_RTOOnR204(target, true);
}
public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsSimpleParticipant_c target, boolean loadComponent)
{
  if (target != null) {
	if(loadComponent){
	     target.loadProxy();
	}
    return target.IsSupertypeReferredToClassInAssoc ;
  } else {
    return null;
  }
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSimpleParticipant_c [] targets,
    ClassQueryInterface_c test)
{
	return getManyR_RTOsOnR204(targets, test, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSimpleParticipant_c [] targets,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if(targets == null || targets.length == 0 || targets[0] == null)
    return new ReferredToClassInAssoc_c[0];
  
  
  LinkedHashSet<ReferredToClassInAssoc_c> elementsSet = new LinkedHashSet<ReferredToClassInAssoc_c>();
  for (int i = 0; i < targets.length; i++) {
	if(loadComponent && targets[i] != null && targets[i].IsSupertypeReferredToClassInAssoc == null)
	  targets[i].loadProxy();
    ReferredToClassInAssoc_c associate = targets[i].IsSupertypeReferredToClassInAssoc;
    if (targets[i] != null && associate != null
    	&& (test == null || test.evaluate(associate))) {
        	if (elementsSet.add(associate)){ 
            }
    }
  }

  ReferredToClassInAssoc_c[] result = new ReferredToClassInAssoc_c[elementsSet.size()];
  elementsSet.toArray(result);
  return result;
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSimpleParticipant_c [] targets)
{
  return getManyR_RTOsOnR204(targets, null);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSimpleParticipant_c target,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if (target != null) {
    ClassAsSimpleParticipant_c [] targetArray = new ClassAsSimpleParticipant_c[1];
    targetArray[0] = target;
    return getManyR_RTOsOnR204(targetArray, test, loadComponent);
  } else {
    ReferredToClassInAssoc_c [] result = new ReferredToClassInAssoc_c [0] ;
    return result ;
  }
  
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSimpleParticipant_c target,
    ClassQueryInterface_c test)
{
    return getManyR_RTOsOnR204(target, null, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSimpleParticipant_c target)
{
    return getManyR_RTOsOnR204(target, null, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsSimpleParticipant_c target, boolean loadComponent)
{
    return getManyR_RTOsOnR204(target, null, loadComponent);
}

  
  
  
// referred to navigation

ClassAsAssociatedOneSide_c backPointer_IsSubtypeClassAsAssociatedOneSideIsSubtype_R204;

public void setClassAsAssociatedOneSideOrderInChildListR204(ClassAsAssociatedOneSide_c target, int index) {
	unrelateAcrossR204From(target);
	ClassAsAssociatedOneSide_c[] elements = ClassAsAssociatedOneSide_c.getManyR_AONEsOnR204(this);
	int count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			unrelateAcrossR204From((ClassAsAssociatedOneSide_c) elements[i]); 
		}
		count++;
	}
	relateAcrossR204To(target);
	count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			relateAcrossR204To((ClassAsAssociatedOneSide_c) elements[i]);
		}
		count++;
	}
}

public void relateAcrossR204To(ClassAsAssociatedOneSide_c target)
{
  if (target != null) {
    target.relateAcrossR204To(this, true) ;
  }
}

public void relateAcrossR204To(ClassAsAssociatedOneSide_c target, boolean notifyChanges)
{
  if (target != null) {
    target.relateAcrossR204To(this, notifyChanges) ;
  }
}

public void setBackPointerR204To(ClassAsAssociatedOneSide_c target)
{
    backPointer_IsSubtypeClassAsAssociatedOneSideIsSubtype_R204 = target;
}

public void unrelateAcrossR204From(ClassAsAssociatedOneSide_c target)
{
  if (target != null) {
    target.unrelateAcrossR204From(this, true) ;
  }
}

public void unrelateAcrossR204From(ClassAsAssociatedOneSide_c target, boolean notifyChanges)
{
  if (target != null) {
    target.unrelateAcrossR204From(this, notifyChanges) ;
  }
}

public void clearBackPointerR204To(ClassAsAssociatedOneSide_c target)
{
	if (target == backPointer_IsSubtypeClassAsAssociatedOneSideIsSubtype_R204) {
		backPointer_IsSubtypeClassAsAssociatedOneSideIsSubtype_R204 = null;
	}
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsAssociatedOneSide_c [] targets)
{
    return getOneR_RTOOnR204(targets, null);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsAssociatedOneSide_c [] targets, ClassQueryInterface_c test)
{
    return getOneR_RTOOnR204(targets, test, true);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsAssociatedOneSide_c [] targets, ClassQueryInterface_c test, boolean loadComponent)
{
    ReferredToClassInAssoc_c ret_val = null;
    if (targets != null)
    {
        for (int i = 0; i < targets.length && ret_val == null; ++i )
        {
           if (test != null) {
             ReferredToClassInAssoc_c candidate_val = getOneR_RTOOnR204(targets[i],true);
             if ( candidate_val != null && test.evaluate(candidate_val) )
             {
               ret_val = candidate_val;
               break;
             }
           }
           else {
             ret_val = getOneR_RTOOnR204(targets[i], loadComponent);
             if (ret_val != null) {
               break;
             }
           }
        }
    }
    return ret_val;
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsAssociatedOneSide_c target)
{
	return getOneR_RTOOnR204(target, true);
}
public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsAssociatedOneSide_c target, boolean loadComponent)
{
  if (target != null) {
	if(loadComponent){
	     target.loadProxy();
	}
    return target.IsSupertypeReferredToClassInAssoc ;
  } else {
    return null;
  }
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOneSide_c [] targets,
    ClassQueryInterface_c test)
{
	return getManyR_RTOsOnR204(targets, test, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOneSide_c [] targets,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if(targets == null || targets.length == 0 || targets[0] == null)
    return new ReferredToClassInAssoc_c[0];
  
  
  LinkedHashSet<ReferredToClassInAssoc_c> elementsSet = new LinkedHashSet<ReferredToClassInAssoc_c>();
  for (int i = 0; i < targets.length; i++) {
	if(loadComponent && targets[i] != null && targets[i].IsSupertypeReferredToClassInAssoc == null)
	  targets[i].loadProxy();
    ReferredToClassInAssoc_c associate = targets[i].IsSupertypeReferredToClassInAssoc;
    if (targets[i] != null && associate != null
    	&& (test == null || test.evaluate(associate))) {
        	if (elementsSet.add(associate)){ 
            }
    }
  }

  ReferredToClassInAssoc_c[] result = new ReferredToClassInAssoc_c[elementsSet.size()];
  elementsSet.toArray(result);
  return result;
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOneSide_c [] targets)
{
  return getManyR_RTOsOnR204(targets, null);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOneSide_c target,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if (target != null) {
    ClassAsAssociatedOneSide_c [] targetArray = new ClassAsAssociatedOneSide_c[1];
    targetArray[0] = target;
    return getManyR_RTOsOnR204(targetArray, test, loadComponent);
  } else {
    ReferredToClassInAssoc_c [] result = new ReferredToClassInAssoc_c [0] ;
    return result ;
  }
  
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOneSide_c target,
    ClassQueryInterface_c test)
{
    return getManyR_RTOsOnR204(target, null, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOneSide_c target)
{
    return getManyR_RTOsOnR204(target, null, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOneSide_c target, boolean loadComponent)
{
    return getManyR_RTOsOnR204(target, null, loadComponent);
}

  
  
  
// referred to navigation

ClassAsAssociatedOtherSide_c backPointer_IsSubtypeClassAsAssociatedOtherSideIsSubtype_R204;

public void setClassAsAssociatedOtherSideOrderInChildListR204(ClassAsAssociatedOtherSide_c target, int index) {
	unrelateAcrossR204From(target);
	ClassAsAssociatedOtherSide_c[] elements = ClassAsAssociatedOtherSide_c.getManyR_AOTHsOnR204(this);
	int count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			unrelateAcrossR204From((ClassAsAssociatedOtherSide_c) elements[i]); 
		}
		count++;
	}
	relateAcrossR204To(target);
	count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			relateAcrossR204To((ClassAsAssociatedOtherSide_c) elements[i]);
		}
		count++;
	}
}

public void relateAcrossR204To(ClassAsAssociatedOtherSide_c target)
{
  if (target != null) {
    target.relateAcrossR204To(this, true) ;
  }
}

public void relateAcrossR204To(ClassAsAssociatedOtherSide_c target, boolean notifyChanges)
{
  if (target != null) {
    target.relateAcrossR204To(this, notifyChanges) ;
  }
}

public void setBackPointerR204To(ClassAsAssociatedOtherSide_c target)
{
    backPointer_IsSubtypeClassAsAssociatedOtherSideIsSubtype_R204 = target;
}

public void unrelateAcrossR204From(ClassAsAssociatedOtherSide_c target)
{
  if (target != null) {
    target.unrelateAcrossR204From(this, true) ;
  }
}

public void unrelateAcrossR204From(ClassAsAssociatedOtherSide_c target, boolean notifyChanges)
{
  if (target != null) {
    target.unrelateAcrossR204From(this, notifyChanges) ;
  }
}

public void clearBackPointerR204To(ClassAsAssociatedOtherSide_c target)
{
	if (target == backPointer_IsSubtypeClassAsAssociatedOtherSideIsSubtype_R204) {
		backPointer_IsSubtypeClassAsAssociatedOtherSideIsSubtype_R204 = null;
	}
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsAssociatedOtherSide_c [] targets)
{
    return getOneR_RTOOnR204(targets, null);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsAssociatedOtherSide_c [] targets, ClassQueryInterface_c test)
{
    return getOneR_RTOOnR204(targets, test, true);
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsAssociatedOtherSide_c [] targets, ClassQueryInterface_c test, boolean loadComponent)
{
    ReferredToClassInAssoc_c ret_val = null;
    if (targets != null)
    {
        for (int i = 0; i < targets.length && ret_val == null; ++i )
        {
           if (test != null) {
             ReferredToClassInAssoc_c candidate_val = getOneR_RTOOnR204(targets[i],true);
             if ( candidate_val != null && test.evaluate(candidate_val) )
             {
               ret_val = candidate_val;
               break;
             }
           }
           else {
             ret_val = getOneR_RTOOnR204(targets[i], loadComponent);
             if (ret_val != null) {
               break;
             }
           }
        }
    }
    return ret_val;
}

public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsAssociatedOtherSide_c target)
{
	return getOneR_RTOOnR204(target, true);
}
public static ReferredToClassInAssoc_c getOneR_RTOOnR204(ClassAsAssociatedOtherSide_c target, boolean loadComponent)
{
  if (target != null) {
	if(loadComponent){
	     target.loadProxy();
	}
    return target.IsSupertypeReferredToClassInAssoc ;
  } else {
    return null;
  }
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOtherSide_c [] targets,
    ClassQueryInterface_c test)
{
	return getManyR_RTOsOnR204(targets, test, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOtherSide_c [] targets,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if(targets == null || targets.length == 0 || targets[0] == null)
    return new ReferredToClassInAssoc_c[0];
  
  
  LinkedHashSet<ReferredToClassInAssoc_c> elementsSet = new LinkedHashSet<ReferredToClassInAssoc_c>();
  for (int i = 0; i < targets.length; i++) {
	if(loadComponent && targets[i] != null && targets[i].IsSupertypeReferredToClassInAssoc == null)
	  targets[i].loadProxy();
    ReferredToClassInAssoc_c associate = targets[i].IsSupertypeReferredToClassInAssoc;
    if (targets[i] != null && associate != null
    	&& (test == null || test.evaluate(associate))) {
        	if (elementsSet.add(associate)){ 
            }
    }
  }

  ReferredToClassInAssoc_c[] result = new ReferredToClassInAssoc_c[elementsSet.size()];
  elementsSet.toArray(result);
  return result;
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOtherSide_c [] targets)
{
  return getManyR_RTOsOnR204(targets, null);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOtherSide_c target,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if (target != null) {
    ClassAsAssociatedOtherSide_c [] targetArray = new ClassAsAssociatedOtherSide_c[1];
    targetArray[0] = target;
    return getManyR_RTOsOnR204(targetArray, test, loadComponent);
  } else {
    ReferredToClassInAssoc_c [] result = new ReferredToClassInAssoc_c [0] ;
    return result ;
  }
  
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOtherSide_c target,
    ClassQueryInterface_c test)
{
    return getManyR_RTOsOnR204(target, null, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOtherSide_c target)
{
    return getManyR_RTOsOnR204(target, null, true);
}

public static ReferredToClassInAssoc_c [] getManyR_RTOsOnR204(ClassAsAssociatedOtherSide_c target, boolean loadComponent)
{
    return getManyR_RTOsOnR204(target, null, loadComponent);
}


      
  public void batchRelate(ModelRoot modelRoot, boolean notifyChanges, boolean searchAllRoots)
  {
      batchRelate(modelRoot, false, notifyChanges, searchAllRoots);
  }
  
  public void batchRelate(ModelRoot modelRoot, boolean relateProxies, boolean notifyChanges, boolean searchAllRoots)
  {
        InstanceList instances=null;
        ModelRoot baseRoot = modelRoot;

      // R203
      ClassInAssociation_c relInst58163 = (ClassInAssociation_c) baseRoot.getInstanceList(ClassInAssociation_c.class).get(new Object[] {m_oir_id,m_obj_id,m_rel_id});
            // if there was no local element, check for any global elements
            // failing that proceed to check other model roots
      		if (relInst58163 == null) {
      			relInst58163 = (ClassInAssociation_c) Ooaofooa.getDefaultInstance().getInstanceList(ClassInAssociation_c.class).get(new Object[] {m_oir_id,m_obj_id,m_rel_id});
      		}
			if (relInst58163 == null && searchAllRoots && !baseRoot.isCompareRoot()) {
				Ooaofooa[] roots = Ooaofooa.getInstances();
				for (int i = 0; i < roots.length; i++) {
				    if(roots[i].isCompareRoot()) {
				         // never use elements from any compare root
				         continue;
				    }
					relInst58163 = (ClassInAssociation_c) roots[i].getInstanceList(ClassInAssociation_c.class).get(new Object[] {m_oir_id,m_obj_id,m_rel_id});
					if (relInst58163 != null)
						break;
				}
			}
			//synchronized
      if ( relInst58163 != null )
      {
          if (relateProxies || !isProxy() || (inSameComponent(this, relInst58163) && !isProxy())) {
	      relInst58163.relateAcrossR203To(this, notifyChanges);
	  }
	  }
	          

	if (IsIdentifiedInThisAssociationByClassIdentifier == null) {          
      // R109
      ClassIdentifier_c relInst58164 = (ClassIdentifier_c) baseRoot.getInstanceList(ClassIdentifier_c.class).get(new Object[] {new UUID(0, new Long(m_oid_id)),m_obj_id});
            // if there was no local element, check for any global elements
            // failing that proceed to check other model roots
      		if (relInst58164 == null) {
      			relInst58164 = (ClassIdentifier_c) Ooaofooa.getDefaultInstance().getInstanceList(ClassIdentifier_c.class).get(new Object[] {new UUID(0, new Long(m_oid_id)),m_obj_id});
      		}
			if (relInst58164 == null && searchAllRoots && !baseRoot.isCompareRoot()) {
				Ooaofooa[] roots = Ooaofooa.getInstances();
				for (int i = 0; i < roots.length; i++) {
				    if(roots[i].isCompareRoot()) {
				         // never use elements from any compare root
				         continue;
				    }
					relInst58164 = (ClassIdentifier_c) roots[i].getInstanceList(ClassIdentifier_c.class).get(new Object[] {new UUID(0, new Long(m_oid_id)),m_obj_id});
					if (relInst58164 != null)
						break;
				}
			}
			//synchronized
      if ( relInst58164 != null )
      {
          if (relateProxies || !isProxy() || (inSameComponent(this, relInst58164) && !isProxy())) {
	      relInst58164.relateAcrossR109To(this, notifyChanges);
	  }
	  }
	}
	          
	}
  public void batchUnrelate(boolean notifyChanges)
  {
		NonRootModelElement inst=null;
      // R203
      // R_OIR
		  inst=IsSupertypeClassInAssociation;
			unrelateAcrossR203From(IsSupertypeClassInAssociation, notifyChanges);
          if ( inst != null ) {
			   inst.removeRef();
	      }
      // R109
      // O_ID
		  inst=IsIdentifiedInThisAssociationByClassIdentifier;
			unrelateAcrossR109From(IsIdentifiedInThisAssociationByClassIdentifier, notifyChanges);
          if ( inst != null ) {
			   inst.removeRef();
	      }
	}
  public static void batchRelateAll(ModelRoot modelRoot, boolean notifyChanges, boolean searchAllRoots) {
		batchRelateAll(modelRoot, notifyChanges, searchAllRoots, false);
  }	  
  public static void batchRelateAll(ModelRoot modelRoot, boolean notifyChanges, boolean searchAllRoots, boolean relateProxies)
  {
	InstanceList instances = modelRoot.getInstanceList(ReferredToClassInAssoc_c.class);
    synchronized(instances) {
        Iterator<NonRootModelElement> cursor = instances.iterator() ;
    	while (cursor.hasNext())
	    {
            final ReferredToClassInAssoc_c inst = (ReferredToClassInAssoc_c)cursor.next() ;
	        inst.batchRelate(modelRoot, relateProxies, notifyChanges, searchAllRoots );
	    }
	}
  }

  public static void clearInstances(ModelRoot modelRoot)
  {
    InstanceList instances = modelRoot.getInstanceList(ReferredToClassInAssoc_c.class);
    synchronized(instances) {
       for(int i=instances.size()-1; i>=0; i--){
              ((NonRootModelElement)instances.get(i)).delete_unchecked();
       }
    
    }
  }

  public static ReferredToClassInAssoc_c ReferredToClassInAssocInstance(ModelRoot modelRoot, ClassQueryInterface_c test, boolean loadComponent)
  {
  		ReferredToClassInAssoc_c result=findReferredToClassInAssocInstance(modelRoot,test,loadComponent);
  		if(result==null && loadComponent){
     List pmcs =  PersistenceManager.findAllComponents(modelRoot,ReferredToClassInAssoc_c.class);
		for (int i = 0; i < pmcs.size(); i++) {
			PersistableModelComponent component = (PersistableModelComponent) pmcs
				.get(i);
			if (!component.isLoaded()) {
				try {
					component.load(new NullProgressMonitor());
					 result=findReferredToClassInAssocInstance(modelRoot,test,loadComponent);
					 if(result!=null) return result;
				} catch (Exception e) {
					CorePlugin.logError("Error Loading component", e);
				}
			}
		}
	    }
	    if(result!=null && loadComponent){
    	    result.loadProxy();
	    }
	  return result;  
  }
private static ReferredToClassInAssoc_c findReferredToClassInAssocInstance(ModelRoot modelRoot, ClassQueryInterface_c test, boolean loadComponent)
{
	InstanceList instances = modelRoot.getInstanceList(ReferredToClassInAssoc_c.class);
		synchronized (instances) {
            for (int i = 0; i < instances.size(); ++i) {
				ReferredToClassInAssoc_c x = (ReferredToClassInAssoc_c) instances.get(i);
				if (test==null || test.evaluate(x)){
					if(x.ensureLoaded(loadComponent))
					return x;
			}
		}
		}
			return null;
}
  public static ReferredToClassInAssoc_c ReferredToClassInAssocInstance(ModelRoot modelRoot, ClassQueryInterface_c test){
     return ReferredToClassInAssocInstance(modelRoot,test,true);
  }
  
  public static ReferredToClassInAssoc_c ReferredToClassInAssocInstance(ModelRoot modelRoot)
  {
	 return ReferredToClassInAssocInstance(modelRoot,null,true);
  }

  public static ReferredToClassInAssoc_c [] ReferredToClassInAssocInstances(ModelRoot modelRoot, ClassQueryInterface_c test, boolean loadComponent)
  {	
            if(loadComponent){
  			   PersistenceManager.ensureAllInstancesLoaded(modelRoot, ReferredToClassInAssoc_c.class);
  			}
		    InstanceList instances = modelRoot.getInstanceList(ReferredToClassInAssoc_c.class);
			Vector matches = new Vector();
			synchronized (instances) {
                for (int i = 0; i < instances.size(); ++i) {
					ReferredToClassInAssoc_c x = (ReferredToClassInAssoc_c) instances.get(i);
					if (test==null ||test.evaluate(x)){
						if(x.ensureLoaded(loadComponent))
						matches.add(x);
			    }
				}
			if (matches.size() > 0) {
				ReferredToClassInAssoc_c[] ret_set = new ReferredToClassInAssoc_c[matches.size()];
				matches.copyInto(ret_set);
				return ret_set;
			} else {
				return new ReferredToClassInAssoc_c[0];
			}		
		} 
  }
  public static ReferredToClassInAssoc_c [] ReferredToClassInAssocInstances(ModelRoot modelRoot, ClassQueryInterface_c test){
    return  ReferredToClassInAssocInstances(modelRoot,test,true);
  }
  public static ReferredToClassInAssoc_c [] ReferredToClassInAssocInstances(ModelRoot modelRoot)
  {
	return ReferredToClassInAssocInstances(modelRoot,null,true);
  }

  public boolean delete()
  {
    boolean result = super.delete();
	boolean delete_error = false;
	String errorMsg = "The following relationships were not torn down by the Referred To Class in Assoc.dispose call: ";
	ClassInAssociation_c testR203Inst2 = ClassInAssociation_c.getOneR_OIROnR203(this, false);

	if ( testR203Inst2 != null )
	{
	delete_error = true;	        
	errorMsg = errorMsg + "203 ";
	}
	ReferredToIdentifierAttribute_c testR110Inst = ReferredToIdentifierAttribute_c.getOneO_RTIDAOnR110(this, false);

	if ( testR110Inst != null )
	{
   	delete_error = true;	        
	errorMsg = errorMsg + "110 ";
	}
	ClassIdentifier_c testR109Inst = ClassIdentifier_c.getOneO_IDOnR109(this, false);

	if ( testR109Inst != null )
	{
   	delete_error = true;	        
	errorMsg = errorMsg + "109 ";
	}
	ClassAsSupertype_c testR204Inst1 = ClassAsSupertype_c.getOneR_SUPEROnR204(this, false);

	if ( testR204Inst1 != null )
	{
	delete_error = true;
	errorMsg = errorMsg + "204 ";
	}
	ClassAsSimpleParticipant_c testR204Inst2 = ClassAsSimpleParticipant_c.getOneR_PARTOnR204(this, false);

	if ( testR204Inst2 != null )
	{
	delete_error = true;
	errorMsg = errorMsg + "204 ";
	}
	ClassAsAssociatedOneSide_c testR204Inst3 = ClassAsAssociatedOneSide_c.getOneR_AONEOnR204(this, false);

	if ( testR204Inst3 != null )
	{
	delete_error = true;
	errorMsg = errorMsg + "204 ";
	}
	ClassAsAssociatedOtherSide_c testR204Inst4 = ClassAsAssociatedOtherSide_c.getOneR_AOTHOnR204(this, false);

	if ( testR204Inst4 != null )
	{
	delete_error = true;
	errorMsg = errorMsg + "204 ";
	}
	if(delete_error == true) {

		if(CorePlugin.getDefault().isDebugging()) {
			Ooaofooa.log.println(ILogger.DELETE, "Referred To Class in Assoc", errorMsg);
		}
		else {
			Exception e = new Exception();
            e.fillInStackTrace();
			CorePlugin.logError(errorMsg, e);
		}
	}
	return result;
  }

  // end declare instance pool

  // declare attribute accessors
  public boolean isUUID(String attributeName){
      if(attributeName.equals("oir_id")){
         return true;
      }
      if(attributeName.equals("obj_id")){
         return true;
      }
      if(attributeName.equals("rel_id")){
         return true;
      }
      return false;      
  }      
 public String getCompUniqueID(){
    UUID tempID=null;
    long longID=0L;
    StringBuffer result= new StringBuffer();
    
    tempID= getOir_id();
    
        if(IdAssigner.NULL_UUID.equals(tempID))
	      tempID=getOir_idCachedValue(); 
	      result.append(Long.toHexString(tempID.getMostSignificantBits()));
          result.append(Long.toHexString(tempID.getLeastSignificantBits()));
    tempID= getObj_id();
    
        if(IdAssigner.NULL_UUID.equals(tempID))
	      tempID=getObj_idCachedValue(); 
	      result.append(Long.toHexString(tempID.getMostSignificantBits()));
          result.append(Long.toHexString(tempID.getLeastSignificantBits()));
    tempID= getRel_id();
    
        if(IdAssigner.NULL_UUID.equals(tempID))
	      tempID=getRel_idCachedValue(); 
	      result.append(Long.toHexString(tempID.getMostSignificantBits()));
          result.append(Long.toHexString(tempID.getLeastSignificantBits()));
    return result.toString();
 }
  // declare attribute accessors
  public long getOir_idLongBased()
  {
    if ( IsSupertypeClassInAssociation != null )
    {
      return IsSupertypeClassInAssociation.getOir_idLongBased();
    }
    return 0;  
  }          
  public java.util.UUID getOir_id()
  {
    if ( IsSupertypeClassInAssociation != null )
    {
      return IsSupertypeClassInAssociation.getOir_id();
    }
    return IdAssigner.NULL_UUID;
  }

 public boolean hasSuperType(){
 	return  ( IsSupertypeClassInAssociation != null );
 
 }                  

  public java.util.UUID getOir_idCachedValue()
  {
    if ( !IdAssigner.NULL_UUID.equals(m_oir_id) )
      return m_oir_id;
    else
      return getOir_id();
  }
  
  public void setOir_id(java.util.UUID newValue)
  {
	if(newValue != null){
	    if(newValue.equals(m_oir_id)){
	        return;
	    }
	}else if(m_oir_id != null){
	    if(m_oir_id.equals(newValue)){
	        return;
	    }
	}else{
	    return;
	}
	AttributeChangeModelDelta change = new AttributeChangeModelDelta(Modeleventnotification_c.DELTA_ATTRIBUTE_CHANGE, this, "Oir_id", m_oir_id, newValue,true); 
   m_oir_id = IdAssigner.preprocessUUID(newValue);
    Ooaofooa.getDefaultInstance().fireModelElementAttributeChanged(change);
  }
  public int getOid_id()
  {
    if ( IsIdentifiedInThisAssociationByClassIdentifier != null )
    {
      return IsIdentifiedInThisAssociationByClassIdentifier.getOid_id();
    }
    return -1;
  }


  public int getOid_idCachedValue()
  {
    if ( m_oid_id != -1 )
      return m_oid_id;
    else
      return getOid_id();
  }
  
  public void setOid_id(int newValue)
  {
    if(m_oid_id == newValue){
        return;
    }
    AttributeChangeModelDelta change = new AttributeChangeModelDelta(Modeleventnotification_c.DELTA_ATTRIBUTE_CHANGE, this, "Oid_id", new Integer(m_oid_id), new Integer(newValue),true);

   m_oid_id = newValue ;
    Ooaofooa.getDefaultInstance().fireModelElementAttributeChanged(change);
  }
  public long getObj_idLongBased()
  {
    if ( IsSupertypeClassInAssociation != null )
    {
      return IsSupertypeClassInAssociation.getObj_idLongBased();
    }
    if ( IsIdentifiedInThisAssociationByClassIdentifier != null )
    {
      return IsIdentifiedInThisAssociationByClassIdentifier.getObj_idLongBased();
    }
    return 0;  
  }          
  public java.util.UUID getObj_id()
  {
    if ( IsSupertypeClassInAssociation != null )
    {
      return IsSupertypeClassInAssociation.getObj_id();
    }
    if ( IsIdentifiedInThisAssociationByClassIdentifier != null )
    {
      return IsIdentifiedInThisAssociationByClassIdentifier.getObj_id();
    }
    return IdAssigner.NULL_UUID;
  }


  public java.util.UUID getObj_idCachedValue()
  {
    if ( !IdAssigner.NULL_UUID.equals(m_obj_id) )
      return m_obj_id;
    else
      return getObj_id();
  }
  
  public long getRel_idLongBased()
  {
    if ( IsSupertypeClassInAssociation != null )
    {
      return IsSupertypeClassInAssociation.getRel_idLongBased();
    }
    return 0;  
  }          
  public java.util.UUID getRel_id()
  {
    if ( IsSupertypeClassInAssociation != null )
    {
      return IsSupertypeClassInAssociation.getRel_id();
    }
    return IdAssigner.NULL_UUID;
  }


  public java.util.UUID getRel_idCachedValue()
  {
    if ( !IdAssigner.NULL_UUID.equals(m_rel_id) )
      return m_rel_id;
    else
      return getRel_id();
  }
  
  public void setRel_id(java.util.UUID newValue)
  {
	if(newValue != null){
	    if(newValue.equals(m_rel_id)){
	        return;
	    }
	}else if(m_rel_id != null){
	    if(m_rel_id.equals(newValue)){
	        return;
	    }
	}else{
	    return;
	}
	AttributeChangeModelDelta change = new AttributeChangeModelDelta(Modeleventnotification_c.DELTA_ATTRIBUTE_CHANGE, this, "Rel_id", m_rel_id, newValue,true); 
   m_rel_id = IdAssigner.preprocessUUID(newValue);
    Ooaofooa.getDefaultInstance().fireModelElementAttributeChanged(change);
  }
  // end declare accessors
  public static void checkClassConsistency (ModelRoot modelRoot) {
    Ooaofooa.log.println(
	  ILogger.OPERATION,
	  "Referred To Class in Assoc", //$NON-NLS-1$
	  " Operation entered: Referred To Class in Assoc::checkClassConsistency"); //$NON-NLS-1$
     if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == false) {  //$NON-NLS-1$
       return;
     }
     ReferredToClassInAssoc_c [] objs = ReferredToClassInAssoc_c.ReferredToClassInAssocInstances(modelRoot,null,false); 
     
     for ( int i = 0; i < objs.length; i++) {
       objs[i].checkConsistency();
     }  
  } 
  public boolean checkConsistency () {
    Ooaofooa.log.println(
	  ILogger.OPERATION,
	  "Referred To Class in Assoc", //$NON-NLS-1$
	  " Operation entered: Referred To Class in Assoc::checkConsistency");  //$NON-NLS-1$
    if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == false) {  //$NON-NLS-1$
      return true;
    }
	ModelRoot modelRoot = getModelRoot();
    boolean      retval = true;
    class ReferredToClassInAssoc_c_test58166_c implements ClassQueryInterface_c
    {
	  ReferredToClassInAssoc_c_test58166_c( java.util.UUID            p58167, java.util.UUID            p58168, java.util.UUID            p58169 ) {
	            m_p58167 = p58167; 
m_p58168 = p58168; 
m_p58169 = p58169;
	  }
	  private java.util.UUID             m_p58167; private java.util.UUID             m_p58168; private java.util.UUID             m_p58169; 
	  public boolean evaluate (Object candidate)
	  {
	      ReferredToClassInAssoc_c selected = (ReferredToClassInAssoc_c) candidate;
	      boolean retval = false;
	      retval = (selected.getOir_id().equals(m_p58167)) & (selected.getObj_id().equals(m_p58168)) & (selected.getRel_id().equals(m_p58169));
	      return retval;
	  }
    }

    ReferredToClassInAssoc_c [] objs58165 = 
    ReferredToClassInAssoc_c.ReferredToClassInAssocInstances(modelRoot, new ReferredToClassInAssoc_c_test58166_c(getOir_id(), getObj_id(), getRel_id())) ;

    if ( (  (objs58165.length) == 0) )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Referred To Class in Assoc", //$NON-NLS-1$
           "Consistency: Object: Referred To Class in Assoc: Cardinality of an identifier is zero. " //$NON-NLS-1$
           + "Actual Value: " + Integer.toString( objs58165.length ) ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Referred To Class in Assoc: Cardinality of an identifier is zero. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs58165.length )  , e); 
      }
      retval = false;

    }

    if ( (  (objs58165.length) > 1) )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Referred To Class in Assoc", //$NON-NLS-1$
           "Consistency: Object: Referred To Class in Assoc: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$
           + "Actual Value: " //$NON-NLS-1$ 
           + Integer.toString( objs58165.length )  + " OIR_ID: " + "Not Printable"  + " Obj_ID: " + "Not Printable"  + " Rel_ID: " + "Not Printable" ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Referred To Class in Assoc: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs58165.length )  + " OIR_ID: " + "Not Printable"  + " Obj_ID: " + "Not Printable"  + " Rel_ID: " + "Not Printable" , e); //$NON-NLS-1$
      }
      retval = false;

    }

    class ReferredToClassInAssoc_c_test58171_c implements ClassQueryInterface_c
    {
	  ReferredToClassInAssoc_c_test58171_c( int             p58172, java.util.UUID            p58173, java.util.UUID            p58174, java.util.UUID            p58175 ) {
	                 m_p58172 = p58172; 
m_p58173 = p58173; 
m_p58174 = p58174; 
m_p58175 = p58175;
	  }
	  private int              m_p58172; private java.util.UUID             m_p58173; private java.util.UUID             m_p58174; private java.util.UUID             m_p58175; 
	  public boolean evaluate (Object candidate)
	  {
	      ReferredToClassInAssoc_c selected = (ReferredToClassInAssoc_c) candidate;
	      boolean retval = false;
	      retval = (selected.getOid_id() == (m_p58172)) & (selected.getOir_id().equals(m_p58173)) & (selected.getObj_id().equals(m_p58174)) & (selected.getRel_id().equals(m_p58175));
	      return retval;
	  }
    }

    ReferredToClassInAssoc_c [] objs58170 = 
    ReferredToClassInAssoc_c.ReferredToClassInAssocInstances(modelRoot, new ReferredToClassInAssoc_c_test58171_c(getOid_id(), getOir_id(), getObj_id(), getRel_id())) ;

    if ( (  (objs58170.length) == 0) )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Referred To Class in Assoc", //$NON-NLS-1$
           "Consistency: Object: Referred To Class in Assoc: Cardinality of an identifier is zero. " //$NON-NLS-1$
           + "Actual Value: " + Integer.toString( objs58170.length ) ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Referred To Class in Assoc: Cardinality of an identifier is zero. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs58170.length )  , e); 
      }
      retval = false;

    }

    if ( (  (objs58170.length) > 1) )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Referred To Class in Assoc", //$NON-NLS-1$
           "Consistency: Object: Referred To Class in Assoc: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$
           + "Actual Value: " //$NON-NLS-1$ 
           + Integer.toString( objs58170.length )  + " Oid_ID: " + Integer.toString(getOid_id())  + " OIR_ID: " + "Not Printable"  + " Obj_ID: " + "Not Printable"  + " Rel_ID: " + "Not Printable" ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Referred To Class in Assoc: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs58170.length )  + " Oid_ID: " + Integer.toString(getOid_id())  + " OIR_ID: " + "Not Printable"  + " Obj_ID: " + "Not Printable"  + " Rel_ID: " + "Not Printable" , e); //$NON-NLS-1$
      }
      retval = false;

    }

          // Referred To Class in Assoc is a subtype in association: rel.Numb = 203
          // The supertype class is: Class In Association
    class ClassInAssociation_c_test58178_c implements ClassQueryInterface_c
    {
	  ClassInAssociation_c_test58178_c( java.util.UUID            p58179, java.util.UUID            p58180, java.util.UUID            p58181 ) {
	            m_p58179 = p58179; 
m_p58180 = p58180; 
m_p58181 = p58181;
	  }
	  private java.util.UUID             m_p58179; private java.util.UUID             m_p58180; private java.util.UUID             m_p58181; 
	  public boolean evaluate (Object candidate)
	  {
	      ClassInAssociation_c selected = (ClassInAssociation_c) candidate;
	      boolean retval = false;
	      retval = (selected.getOir_id().equals(m_p58179)) & (selected.getObj_id().equals(m_p58180)) & (selected.getRel_id().equals(m_p58181));
	      return retval;
	  }
    }

    ClassInAssociation_c [] objs58177 = 
    ClassInAssociation_c.ClassInAssociationInstances(modelRoot, new ClassInAssociation_c_test58178_c(getOir_id(), getObj_id(), getRel_id())) ;

    if ( (  (objs58177.length) != 1) )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Referred To Class in Assoc", //$NON-NLS-1$
           "Consistency: Object: Referred To Class in Assoc: Association: 203: Cardinality of a supertype is not equal to 1. " //$NON-NLS-1$
           + "Actual Value: " + Integer.toString( objs58177.length ) ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Referred To Class in Assoc: Association: 203: Cardinality of a supertype is not equal to 1. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs58177.length )  , e); 
      }
      retval = false;

    }

          // Referred To Class in Assoc is a referring class in association: rel.Numb = 109
          // The participating class is: Class Identifier
    class ClassIdentifier_c_test58183_c implements ClassQueryInterface_c
    {
	  ClassIdentifier_c_test58183_c( java.util.UUID            p58184, int             p58185 ) {
	       m_p58184 = p58184; 
m_p58185 = p58185;
	  }
	  private java.util.UUID             m_p58184; private int              m_p58185; 
	  public boolean evaluate (Object candidate)
	  {
	      ClassIdentifier_c selected = (ClassIdentifier_c) candidate;
	      boolean retval = false;
	      retval = (selected.getObj_id().equals(m_p58184)) & (selected.getOid_id() == (m_p58185));
	      return retval;
	  }
    }

    ClassIdentifier_c [] objs58182 = 
    ClassIdentifier_c.ClassIdentifierInstances(modelRoot, new ClassIdentifier_c_test58183_c(getObj_id(), getOid_id())) ;

    if ( (  (objs58182.length) > 1) )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Referred To Class in Assoc", //$NON-NLS-1$
           "Consistency: Object: Referred To Class in Assoc: Association: 109: Cardinality of a participant is greater than 1. " //$NON-NLS-1$
           + "Actual Value: " //$NON-NLS-1$ 
           + Integer.toString( objs58182.length )  + " Obj_ID: " + "Not Printable"  + " Oid_ID: " + Integer.toString(getOid_id()) ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Referred To Class in Assoc: Association: 109: Cardinality of a participant is greater than 1. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs58182.length )  + " Obj_ID: " + "Not Printable"  + " Oid_ID: " + Integer.toString(getOid_id()) , e); //$NON-NLS-1$
      }
      retval = false;

    }
                
          // Supertype: rel.Numb = 204
    int objs58186 = 0;
            // Subtype Object: Class As Supertype
    class ClassAsSupertype_c_test58187_c implements ClassQueryInterface_c
    {
	  ClassAsSupertype_c_test58187_c( java.util.UUID            p58188, java.util.UUID            p58189, java.util.UUID            p58190 ) {
	            m_p58188 = p58188; 
m_p58189 = p58189; 
m_p58190 = p58190;
	  }
	  private java.util.UUID             m_p58188; private java.util.UUID             m_p58189; private java.util.UUID             m_p58190; 
	  public boolean evaluate (Object candidate)
	  {
	      ClassAsSupertype_c selected = (ClassAsSupertype_c) candidate;
	      boolean retval = false;
	      retval = (selected.getOir_id().equals(m_p58188)) & (selected.getObj_id().equals(m_p58189)) & (selected.getRel_id().equals(m_p58190));
	      return retval;
	  }
    }

    ClassAsSupertype_c [] objs58191 = 
    ClassAsSupertype_c.ClassAsSupertypeInstances(modelRoot, new ClassAsSupertype_c_test58187_c(getOir_id(), getObj_id(), getRel_id())) ;
 
    objs58186 = objs58186 + objs58191.length;
            // Subtype Object: Class As Simple Participant
    class ClassAsSimpleParticipant_c_test58192_c implements ClassQueryInterface_c
    {
	  ClassAsSimpleParticipant_c_test58192_c( java.util.UUID            p58193, java.util.UUID            p58194, java.util.UUID            p58195 ) {
	            m_p58193 = p58193; 
m_p58194 = p58194; 
m_p58195 = p58195;
	  }
	  private java.util.UUID             m_p58193; private java.util.UUID             m_p58194; private java.util.UUID             m_p58195; 
	  public boolean evaluate (Object candidate)
	  {
	      ClassAsSimpleParticipant_c selected = (ClassAsSimpleParticipant_c) candidate;
	      boolean retval = false;
	      retval = (selected.getOir_id().equals(m_p58193)) & (selected.getObj_id().equals(m_p58194)) & (selected.getRel_id().equals(m_p58195));
	      return retval;
	  }
    }

    ClassAsSimpleParticipant_c [] objs58196 = 
    ClassAsSimpleParticipant_c.ClassAsSimpleParticipantInstances(modelRoot, new ClassAsSimpleParticipant_c_test58192_c(getOir_id(), getObj_id(), getRel_id())) ;
 
    objs58186 = objs58186 + objs58196.length;
            // Subtype Object: Class As Associated One Side
    class ClassAsAssociatedOneSide_c_test58197_c implements ClassQueryInterface_c
    {
	  ClassAsAssociatedOneSide_c_test58197_c( java.util.UUID            p58198, java.util.UUID            p58199, java.util.UUID            p58200 ) {
	            m_p58198 = p58198; 
m_p58199 = p58199; 
m_p58200 = p58200;
	  }
	  private java.util.UUID             m_p58198; private java.util.UUID             m_p58199; private java.util.UUID             m_p58200; 
	  public boolean evaluate (Object candidate)
	  {
	      ClassAsAssociatedOneSide_c selected = (ClassAsAssociatedOneSide_c) candidate;
	      boolean retval = false;
	      retval = (selected.getOir_id().equals(m_p58198)) & (selected.getObj_id().equals(m_p58199)) & (selected.getRel_id().equals(m_p58200));
	      return retval;
	  }
    }

    ClassAsAssociatedOneSide_c [] objs58201 = 
    ClassAsAssociatedOneSide_c.ClassAsAssociatedOneSideInstances(modelRoot, new ClassAsAssociatedOneSide_c_test58197_c(getOir_id(), getObj_id(), getRel_id())) ;
 
    objs58186 = objs58186 + objs58201.length;
            // Subtype Object: Class As Associated Other Side
    class ClassAsAssociatedOtherSide_c_test58202_c implements ClassQueryInterface_c
    {
	  ClassAsAssociatedOtherSide_c_test58202_c( java.util.UUID            p58203, java.util.UUID            p58204, java.util.UUID            p58205 ) {
	            m_p58203 = p58203; 
m_p58204 = p58204; 
m_p58205 = p58205;
	  }
	  private java.util.UUID             m_p58203; private java.util.UUID             m_p58204; private java.util.UUID             m_p58205; 
	  public boolean evaluate (Object candidate)
	  {
	      ClassAsAssociatedOtherSide_c selected = (ClassAsAssociatedOtherSide_c) candidate;
	      boolean retval = false;
	      retval = (selected.getOir_id().equals(m_p58203)) & (selected.getObj_id().equals(m_p58204)) & (selected.getRel_id().equals(m_p58205));
	      return retval;
	  }
    }

    ClassAsAssociatedOtherSide_c [] objs58206 = 
    ClassAsAssociatedOtherSide_c.ClassAsAssociatedOtherSideInstances(modelRoot, new ClassAsAssociatedOtherSide_c_test58202_c(getOir_id(), getObj_id(), getRel_id())) ;
 
    objs58186 = objs58186 + objs58206.length;
    if ( objs58186 != 1 )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Referred To Class in Assoc", //$NON-NLS-1$
           "Consistency: Object: Referred To Class in Assoc: Association: 204: Cardinality of subtype is not equal to 1. " //$NON-NLS-1$
           + "Actual Value: " + Integer.toString( objs58186 ) ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Referred To Class in Assoc: Association: 204: Cardinality of subtype is not equal to 1. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs58186 )  , e); 
      }
      retval = false;

    }

          // Associated One Side: rel.Numb = 110
            // Link Object: Referred To Identifier Attribute
            // Other Side Class: Class Identifier Attribute
    return retval;
  }


  // declare transform functions
  public  void Dispose()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Referred To Class in Assoc", " Operation entered: ReferredToClassInAssoc::Dispose") ; 
               final ModelRoot modelRoot = getModelRoot();
ClassAsSupertype_c v_zuper = ClassAsSupertype_c.getOneR_SUPEROnR204(this);


ClassAsAssociatedOneSide_c v_one = ClassAsAssociatedOneSide_c.getOneR_AONEOnR204(this);


ClassAsAssociatedOtherSide_c v_other = ClassAsAssociatedOtherSide_c.getOneR_AOTHOnR204(this);


ClassAsSimpleParticipant_c v_part = ClassAsSimpleParticipant_c.getOneR_PARTOnR204(this);


if ( (  (v_zuper != null)) )
{

if (v_zuper != null) {
v_zuper.Dispose() ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Attempted to call an operation on a null instance.", t);
}



}

else if ( (  (v_one != null)) )
{

if (v_one != null) {
v_one.Dispose() ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Attempted to call an operation on a null instance.", t);
}



}

else if ( (  (v_other != null)) )
{

if (v_other != null) {
v_other.Dispose() ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Attempted to call an operation on a null instance.", t);
}



}

else if ( (  (v_part != null)) )
{

if (v_part != null) {
v_part.Dispose() ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Attempted to call an operation on a null instance.", t);
}



}

ClassInAssociation_c v_cia = ClassInAssociation_c.getOneR_OIROnR203(this);


if ( (  (v_cia != null)) )
{

this.unrelateAcrossR203From(v_cia);



}

ClassIdentifier_c v_oid = ClassIdentifier_c.getOneO_IDOnR109(this);


if ( (  (v_oid != null)) )
{

this.unrelateAcrossR109From(v_oid);



}

ReferredToIdentifierAttribute_c [] v_rtidas = ReferredToIdentifierAttribute_c.getManyO_RTIDAsOnR110(this);


ReferredToIdentifierAttribute_c  v_rtida = null;
for ( int i55427 = 0; i55427 < v_rtidas.length; i55427++)
{
  v_rtida = v_rtidas[i55427] ;

if (v_rtida != null) {
v_rtida.Dispose() ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Attempted to call an operation on a null instance.", t);
}



}

if ( delete() ) {
    Ooaofooa.getDefaultInstance().fireModelElementDeleted(new BaseModelDelta(Modeleventnotification_c.DELTA_DELETE, this));
}



   } // End dispose
  public  void Unformalize()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Referred To Class in Assoc", " Operation entered: ReferredToClassInAssoc::Unformalize") ; 
               final ModelRoot modelRoot = getModelRoot();
ReferredToIdentifierAttribute_c [] v_rtida_set = ReferredToIdentifierAttribute_c.getManyO_RTIDAsOnR110(this);


ReferredToIdentifierAttribute_c  v_rtida = null;
for ( int i55428 = 0; i55428 < v_rtida_set.length; i55428++)
{
  v_rtida = v_rtida_set[i55428] ;

AttributeReferenceInClass_c [] v_ref_set = AttributeReferenceInClass_c.getManyO_REFsOnR111(v_rtida);


AttributeReferenceInClass_c  v_ref = null;
for ( int i55429 = 0; i55429 < v_ref_set.length; i55429++)
{
  v_ref = v_ref_set[i55429] ;

if (v_ref != null) {
v_ref.Migraterefattrordispose() ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Attempted to call an operation on a null instance.", t);
}



}

ClassIdentifierAttribute_c v_oida = ClassIdentifierAttribute_c.getOneO_OIDAOnR110(v_rtida);


if (v_rtida != null) {
v_rtida.unrelateAcrossR110From( v_oida ) ; v_rtida.unrelateAcrossR110From( this ) ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Unrelate using attempted on null link class instance.", t);
}


if (v_rtida != null) {
// get the location of this element in the instance list
// before deleting
if ( v_rtida.delete() ) {
    Ooaofooa.getDefaultInstance().fireModelElementDeleted(new BaseModelDelta(Modeleventnotification_c.DELTA_DELETE, v_rtida));
}
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Delete attempted on null instance.", t);
}



}

ClassIdentifier_c v_oid = ClassIdentifier_c.getOneO_IDOnR109(this);


if (v_oid != null) {
v_oid.unrelateAcrossR109From(this);
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Unrelate attempted on null left hand instance.", t);
}



   } // End unformalize
  public  void Addattributetoidentifier(final java.util.UUID         p_Attr_id)
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Referred To Class in Assoc", " Operation entered: ReferredToClassInAssoc::Addattributetoidentifier") ; 
               final ModelRoot modelRoot = getModelRoot();
  class ClassIdentifierAttribute_test55986_c implements ClassQueryInterface_c
  {
	public boolean evaluate (Object candidate)
	{
		ClassIdentifierAttribute_c selected = (ClassIdentifierAttribute_c)candidate;
		return selected.getAttr_id().equals(p_Attr_id) ;
	}
  }
ClassIdentifierAttribute_c v_oida = ClassIdentifierAttribute_c.getOneO_OIDAOnR105(ClassIdentifier_c.getManyO_IDsOnR109(this), new ClassIdentifierAttribute_test55986_c());


if ( (  (v_oida != null)) )
{

  class ReferringClassInAssoc_test55987_c implements ClassQueryInterface_c
  {
	ReferringClassInAssoc_test55987_c( java.util.UUID         p55988, java.util.UUID         p55989 ) {
		m_p55988 = p55988;
				m_p55989 = p55989;
	}
	private java.util.UUID         m_p55988;
		private java.util.UUID         m_p55989;
	public boolean evaluate (Object candidate)
	{
		ReferringClassInAssoc_c selected = (ReferringClassInAssoc_c)candidate;
		return (! selected.getOir_id().equals(m_p55988) && selected.getRel_id().equals(m_p55989)) ;
	}
  }
ReferringClassInAssoc_c [] v_rgo_set = ReferringClassInAssoc_c.getManyR_RGOsOnR203(ClassInAssociation_c.getManyR_OIRsOnR201(Association_c.getManyR_RELsOnR201(ClassInAssociation_c.getManyR_OIRsOnR203(this))), new ReferringClassInAssoc_test55987_c(getOir_id(), getRel_id()));


ReferringClassInAssoc_c  v_rgo = null;
for ( int i55430 = 0; i55430 < v_rgo_set.length; i55430++)
{
  v_rgo = v_rgo_set[i55430] ;

ClassIdentifierAttribute_c v_ref_attr_id = ClassIdentifierAttribute_c.getOneO_OIDAOnR105(Attribute_c.getManyO_ATTRsOnR106(ReferentialAttribute_c.getManyO_RATTRsOnR108(AttributeReferenceInClass_c.getManyO_REFsOnR111(v_rgo))));


int          v_id_id = -1 ;


if ( (  (v_ref_attr_id != null)) )
{

LinkedAssociation_c v_assoc = LinkedAssociation_c.getOneR_ASSOCOnR206(Association_c.getOneR_RELOnR201(ClassInAssociation_c.getOneR_OIROnR203(v_rgo)));


SubtypeSupertypeAssociation_c v_subsup = SubtypeSupertypeAssociation_c.getOneR_SUBSUPOnR206(Association_c.getOneR_RELOnR201(ClassInAssociation_c.getOneR_OIROnR203(v_rgo)));


if (   (v_assoc != null) ||   (v_subsup != null) )
{

v_id_id = v_ref_attr_id.getOid_id() ;



}


}

java.util.UUID         v_newAttr_id = v_oida.Addreference(			    
v_id_id			    
,getRel_id()			    
,v_rgo.getObj_id()			    
,v_rgo.getOir_id()			    
,getObj_id()			    
,getOir_id()) ;


if ( (v_id_id != -1) )
{

ReferredToClassInAssoc_c [] v_rto_set = ReferredToClassInAssoc_c.getManyR_RTOsOnR109(ClassIdentifier_c.getManyO_IDsOnR105(v_ref_attr_id));


ReferredToClassInAssoc_c  v_rto = null;
for ( int i55431 = 0; i55431 < v_rto_set.length; i55431++)
{
  v_rto = v_rto_set[i55431] ;

if (v_rto != null) {
v_rto.Addattributetoidentifier(			    
v_newAttr_id ) ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Attempted to call an operation on a null instance.", t);
}



}


}


}


}


   } // End addAttributeToIdentifier

  // end transform functions


  public Object getAdapter(Class adapter) {
    Object superAdapter = super.getAdapter(adapter);
    if(superAdapter != null) {
    	return superAdapter;
    }
	  return null;
  }
} // end Referred To Class in Assoc
