--========================================================================
--
-- File: metamodel_schema.sql
--
-- WARNING:      Do not edit this generated file
-- Generated by: ../../MC-Java/schema_gen.arc
-- Version:      $Revision: 1.17 $
--
--(c) Copyright 2005-2014 by Mentor Graphics Corp. All rights reserved.
--
--========================================================================
-- Licensed under the Apache License, Version 2.0 (the "License"); you may not
-- use this file except in compliance with the License.  You may obtain a copy
-- of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
-- WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   See the
-- License for the specific language governing permissions and limitations under
-- the License.
--======================================================================== 
--

CREATE TABLE S_AW (
	     Brg_ID	UNIQUE_ID,
	     Sync_ID	UNIQUE_ID );
CREATE TABLE O_RTIDA (
	     Attr_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID,
	     Oid_ID	INTEGER,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID );
CREATE TABLE O_RATTR (
	     Attr_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID,
	     BAttr_ID	UNIQUE_ID,
	     BObj_ID	UNIQUE_ID,
	     Ref_Mode	INTEGER,
	     BaseAttrName	STRING );
CREATE TABLE O_TPARM (
	     TParm_ID	UNIQUE_ID,
	     Tfr_ID	UNIQUE_ID,
	     Name	STRING,
	     DT_ID	UNIQUE_ID,
	     By_Ref	INTEGER,
	     Dimensions	STRING,
	     Previous_TParm_ID	UNIQUE_ID,
	     Descrip	STRING );
CREATE TABLE O_TFR (
	     Tfr_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     DT_ID	UNIQUE_ID,
	     Instance_Based	INTEGER,
	     Action_Semantics_internal	STRING,
	     Suc_Pars	INTEGER,
	     Return_Dimensions	STRING,
	     Previous_Tfr_ID	UNIQUE_ID );
CREATE TABLE O_NBATTR (
	     Attr_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID );
CREATE TABLE O_OBJ (
	     Obj_ID	UNIQUE_ID,
	     Name	STRING,
	     Numb	INTEGER,
	     Key_Lett	STRING,
	     Descrip	STRING,
	     SS_ID	UNIQUE_ID );
CREATE TABLE O_IOBJ (
	     IObj_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID,
	     Modl_Typ	INTEGER,
	     SS_ID	UNIQUE_ID,
	     Obj_Name	STRING,
	     Obj_KL	STRING );
CREATE TABLE O_DBATTR (
	     Attr_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID,
	     Action_Semantics_internal	STRING,
	     Suc_Pars	INTEGER );
CREATE TABLE O_OIDA (
	     Attr_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID,
	     Oid_ID	INTEGER,
	     localAttributeName	STRING );
CREATE TABLE O_ID (
	     Oid_ID	INTEGER,
	     Obj_ID	UNIQUE_ID );
CREATE TABLE O_BATTR (
	     Attr_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID );
CREATE TABLE O_REF (
	     Obj_ID	UNIQUE_ID,
	     RObj_ID	UNIQUE_ID,
	     ROid_ID	INTEGER,
	     RAttr_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID,
	     ROIR_ID	UNIQUE_ID,
	     Attr_ID	UNIQUE_ID,
	     ARef_ID	UNIQUE_ID,
	     PARef_ID	UNIQUE_ID,
	     Is_Cstrd	INTEGER,
	     Descrip	STRING,
	     RObj_Name	STRING,
	     RAttr_Name	STRING,
	     Rel_Name	STRING );
CREATE TABLE O_ATTR (
	     Attr_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID,
	     PAttr_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     Prefix	STRING,
	     Root_Nam	STRING,
	     Pfx_Mode	INTEGER,
	     DT_ID	UNIQUE_ID,
	     Dimensions	STRING,
	     DefaultValue	STRING );
CREATE TABLE SM_TAH (
	     Act_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     Trans_ID	UNIQUE_ID );
CREATE TABLE SM_TXN (
	     Trans_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMstt_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID );
CREATE TABLE SM_SDI (
	     SMedi_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID );
CREATE TABLE SM_STATE (
	     SMstt_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID,
	     Name	STRING,
	     Numb	INTEGER,
	     Final	INTEGER );
CREATE TABLE SM_EVTDI (
	     SMedi_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     DT_ID	UNIQUE_ID,
	     Dimensions	STRING,
	     SMevt_ID	UNIQUE_ID,
	     Previous_SMedi_ID	UNIQUE_ID );
CREATE TABLE SM_EVT (
	     SMevt_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID,
	     Numb	INTEGER,
	     Mning	STRING,
	     Is_Lbl_U	INTEGER,
	     Unq_Lbl	STRING,
	     Drv_Lbl	STRING,
	     Descrip	STRING );
CREATE TABLE SM_SM (
	     SM_ID	UNIQUE_ID,
	     Descrip	STRING,
	     Config_ID	INTEGER );
CREATE TABLE SM_SEME (
	     SMstt_ID	UNIQUE_ID,
	     SMevt_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID );
CREATE TABLE SM_SGEVT (
	     SMevt_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID,
	     Provided_Signal_Id	UNIQUE_ID,
	     Required_Signal_Id	UNIQUE_ID,
	     signal_name	STRING );
CREATE TABLE SM_SEVT (
	     SMevt_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID );
CREATE TABLE SM_PEVT (
	     SMevt_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID,
	     localClassName	STRING,
	     localClassKL	STRING,
	     localEventMning	STRING );
CREATE TABLE SM_NLEVT (
	     SMevt_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID,
	     polySMevt_ID	UNIQUE_ID,
	     polySM_ID	UNIQUE_ID,
	     polySMspd_ID	UNIQUE_ID,
	     Local_Meaning	STRING );
CREATE TABLE SM_NETXN (
	     Trans_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMstt_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID );
CREATE TABLE SM_NSTXN (
	     Trans_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMstt_ID	UNIQUE_ID,
	     SMevt_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID );
CREATE TABLE SM_MOORE (
	     SM_ID	UNIQUE_ID );
CREATE TABLE SM_MOAH (
	     Act_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMstt_ID	UNIQUE_ID );
CREATE TABLE SM_MEALY (
	     SM_ID	UNIQUE_ID );
CREATE TABLE SM_MEAH (
	     Act_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     Trans_ID	UNIQUE_ID );
CREATE TABLE SM_LEVT (
	     SMevt_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID );
CREATE TABLE SM_ISM (
	     SM_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID );
CREATE TABLE SM_SUPDT (
	     SMspd_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     Non_Local	INTEGER );
CREATE TABLE SM_EIGN (
	     SMstt_ID	UNIQUE_ID,
	     SMevt_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID,
	     Descrip	STRING );
CREATE TABLE SM_CRTXN (
	     Trans_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMevt_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID );
CREATE TABLE SM_ASM (
	     SM_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID );
CREATE TABLE SM_CH (
	     SMstt_ID	UNIQUE_ID,
	     SMevt_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMspd_ID	UNIQUE_ID,
	     Descrip	STRING );
CREATE TABLE SM_AH (
	     Act_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID );
CREATE TABLE SM_ACT (
	     Act_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     Suc_Pars	INTEGER,
	     Action_Semantics_internal	STRING,
	     Descrip	STRING );
CREATE TABLE SR_SR (
	     Id	UNIQUE_ID,
	     Engine_Id	UNIQUE_ID,
	     MatchedParticipant_Id	UNIQUE_ID );
CREATE TABLE SR_NM (
	     Id	UNIQUE_ID,
	     Unnamed_Attribute	INTEGER );
CREATE TABLE SR_M (
	     Id	UNIQUE_ID,
	     Result_Id	UNIQUE_ID );
CREATE TABLE SR_CMR (
	     Id	UNIQUE_ID,
	     startPosition	INTEGER,
	     length	INTEGER );
CREATE TABLE SR_CM (
	     Id	UNIQUE_ID,
	     startPosition	INTEGER,
	     matchLength	INTEGER );
CREATE TABLE SQU_R (
	     Id	UNIQUE_ID );
CREATE TABLE SQU_Q (
	     Id	UNIQUE_ID,
	     Engine_Id	UNIQUE_ID,
	     pattern	STRING,
	     regEx	INTEGER,
	     caseSensitive	INTEGER,
	     scope	INTEGER );
CREATE TABLE SQU_DE (
	     Id	UNIQUE_ID );
CREATE TABLE SQU_D (
	     Id	UNIQUE_ID );
CREATE TABLE SQU_A (
	     Id	UNIQUE_ID );
CREATE TABLE SP_SE (
	     Id	UNIQUE_ID,
	     Participant_Id	UNIQUE_ID,
	     modelRootId	STRING,
	     className	STRING,
	     elementId	INTEGER );
CREATE TABLE SP_SP (
	     Id	UNIQUE_ID,
	     Engine_Id	UNIQUE_ID );
CREATE TABLE SP_NS (
	     Id	UNIQUE_ID,
	     searchableValue	STRING );
CREATE TABLE SP_DS (
	     Id	UNIQUE_ID,
	     searchableValue	STRING );
CREATE TABLE SP_ALS (
	     Id	UNIQUE_ID,
	     searchableValue	STRING );
CREATE TABLE SEN_E (
	     Id	UNIQUE_ID );
CREATE TABLE SEN_RE (
	     Id	UNIQUE_ID );
CREATE TABLE SEN_DE (
	     Id	UNIQUE_ID );
CREATE TABLE SEN_DCE (
	     Id	UNIQUE_ID );
CREATE TABLE SEN_ALE (
	     Id	UNIQUE_ID );
CREATE TABLE PE_PE (
	     Element_ID	UNIQUE_ID,
	     Visibility	INTEGER,
	     Package_ID	UNIQUE_ID,
	     Component_ID	UNIQUE_ID,
	     type	INTEGER );
CREATE TABLE G_EIS (
	     Element_ID	UNIQUE_ID,
	     Sys_ID	UNIQUE_ID );
CREATE TABLE EP_SPKG (
	     Package_ID	UNIQUE_ID,
	     Container_Package_ID	UNIQUE_ID );
CREATE TABLE EP_PIP (
	     Parent_Package_ID	UNIQUE_ID,
	     Child_Package_ID	UNIQUE_ID );
CREATE TABLE EP_PKG (
	     Package_ID	UNIQUE_ID,
	     Sys_ID	UNIQUE_ID,
	     Direct_Sys_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     Num_Rng	INTEGER );
CREATE TABLE S_UDT (
	     DT_ID	UNIQUE_ID,
	     CDT_DT_ID	UNIQUE_ID,
	     Gen_Type	INTEGER );
CREATE TABLE S_SYS (
	     Sys_ID	UNIQUE_ID,
	     Name	STRING,
	     useGlobals	INTEGER );
CREATE TABLE S_SIS (
	     Parent_SS_ID	UNIQUE_ID,
	     Child_SS_ID	UNIQUE_ID );
CREATE TABLE S_SID (
	     Dom_ID	UNIQUE_ID,
	     SS_ID	UNIQUE_ID );
CREATE TABLE S_SS (
	     SS_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     Prefix	STRING,
	     Num_Rng	INTEGER,
	     Dom_ID	UNIQUE_ID,
	     Config_ID	UNIQUE_ID );
CREATE TABLE S_SDT (
	     DT_ID	UNIQUE_ID );
CREATE TABLE S_MBR (
	     Member_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     Parent_DT_DT_ID	UNIQUE_ID,
	     DT_ID	UNIQUE_ID,
	     Previous_Member_ID	UNIQUE_ID,
	     Dimensions	STRING );
CREATE TABLE S_IRDT (
	     DT_ID	UNIQUE_ID,
	     isSet	INTEGER,
	     Obj_ID	UNIQUE_ID );
CREATE TABLE S_SPARM (
	     SParm_ID	UNIQUE_ID,
	     Sync_ID	UNIQUE_ID,
	     Name	STRING,
	     DT_ID	UNIQUE_ID,
	     By_Ref	INTEGER,
	     Dimensions	STRING,
	     Previous_SParm_ID	UNIQUE_ID,
	     Descrip	STRING );
CREATE TABLE S_FPIP (
	     FunPack_ID	UNIQUE_ID );
CREATE TABLE S_FPK (
	     FunPack_ID	UNIQUE_ID,
	     Name	STRING,
	     Dom_ID	UNIQUE_ID,
	     Parent_FunPack_ID	UNIQUE_ID );
CREATE TABLE S_FIP (
	     FunPack_ID	UNIQUE_ID,
	     Sync_ID	UNIQUE_ID );
CREATE TABLE S_SYNC (
	     Sync_ID	UNIQUE_ID,
	     Dom_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     Action_Semantics_internal	STRING,
	     DT_ID	UNIQUE_ID,
	     Suc_Pars	INTEGER,
	     Return_Dimensions	STRING );
CREATE TABLE S_EEPK (
	     EEPack_ID	UNIQUE_ID,
	     Name	STRING,
	     Dom_ID	UNIQUE_ID,
	     Parent_EEPack_ID	UNIQUE_ID );
CREATE TABLE S_EEIP (
	     EEPack_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID );
CREATE TABLE S_EEM (
	     EEmod_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID,
	     Modl_Typ	INTEGER,
	     SS_ID	UNIQUE_ID );
CREATE TABLE S_EEEDI (
	     EEedi_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     DT_ID	UNIQUE_ID );
CREATE TABLE S_EEEDT (
	     EE_ID	UNIQUE_ID,
	     EEevt_ID	UNIQUE_ID,
	     EEedi_ID	UNIQUE_ID );
CREATE TABLE S_EEEVT (
	     EEevt_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID,
	     Numb	INTEGER,
	     Mning	STRING,
	     Is_Lbl_U	INTEGER,
	     Unq_Lbl	STRING,
	     Drv_Lbl	STRING,
	     Descrip	STRING );
CREATE TABLE S_EEDI (
	     EEdi_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     DT_ID	UNIQUE_ID );
CREATE TABLE S_EE (
	     EE_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     Key_Lett	STRING,
	     Dom_ID	UNIQUE_ID,
	     Realized_Class_Path	STRING,
	     Label	STRING,
	     isRealized	INTEGER );
CREATE TABLE S_ENUM (
	     Enum_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     EDT_DT_ID	UNIQUE_ID,
	     Previous_Enum_ID	UNIQUE_ID );
CREATE TABLE S_EDT (
	     DT_ID	UNIQUE_ID );
CREATE TABLE S_EEPIP (
	     EEPack_ID	UNIQUE_ID );
CREATE TABLE S_DOM (
	     Dom_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     Full_Der	INTEGER,
	     Config_ID	UNIQUE_ID,
	     Sys_ID	UNIQUE_ID );
CREATE TABLE S_DIM (
	     elementCount	INTEGER,
	     dimensionCount	INTEGER,
	     Sync_ID	UNIQUE_ID,
	     SParm_ID	UNIQUE_ID,
	     BParm_ID	UNIQUE_ID,
	     Brg_ID	UNIQUE_ID,
	     Id	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID,
	     Attr_ID	UNIQUE_ID,
	     TParm_ID	UNIQUE_ID,
	     Tfr_ID	UNIQUE_ID,
	     Member_ID	UNIQUE_ID,
	     DT_ID	UNIQUE_ID,
	     PP_Id	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     SMedi_ID	UNIQUE_ID,
	     DIM_ID	UNIQUE_ID,
	     Var_ID	UNIQUE_ID );
CREATE TABLE S_DIS (
	     Dom_ID	UNIQUE_ID,
	     DT_ID	UNIQUE_ID );
CREATE TABLE S_DPIP (
	     Package_ID	UNIQUE_ID );
CREATE TABLE S_DPK (
	     Package_ID	UNIQUE_ID,
	     Name	STRING,
	     Dom_ID	UNIQUE_ID,
	     Parent_Package_ID	UNIQUE_ID );
CREATE TABLE S_DIP (
	     Package_ID	UNIQUE_ID,
	     DT_ID	UNIQUE_ID );
CREATE TABLE S_DT (
	     DT_ID	UNIQUE_ID,
	     Dom_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     DefaultValue	STRING );
CREATE TABLE S_CDT (
	     DT_ID	UNIQUE_ID,
	     Core_Typ	INTEGER );
CREATE TABLE S_BPARM (
	     BParm_ID	UNIQUE_ID,
	     Brg_ID	UNIQUE_ID,
	     Name	STRING,
	     DT_ID	UNIQUE_ID,
	     By_Ref	INTEGER,
	     Dimensions	STRING,
	     Previous_BParm_ID	UNIQUE_ID,
	     Descrip	STRING );
CREATE TABLE S_BRG (
	     Brg_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     Brg_Typ	INTEGER,
	     DT_ID	UNIQUE_ID,
	     Action_Semantics_internal	STRING,
	     Suc_Pars	INTEGER,
	     Return_Dimensions	STRING );
CREATE TABLE CNST_SYC (
	     Const_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING,
	     DT_ID	UNIQUE_ID,
	     Constant_Spec_ID	UNIQUE_ID,
	     Previous_Const_ID	UNIQUE_ID,
	     Previous_DT_DT_ID	UNIQUE_ID );
CREATE TABLE CNST_LSC (
	     Const_ID	UNIQUE_ID,
	     DT_ID	UNIQUE_ID,
	     Value	STRING );
CREATE TABLE CNST_LFSC (
	     Const_ID	UNIQUE_ID,
	     DT_ID	UNIQUE_ID );
CREATE TABLE CNST_CSP (
	     Constant_Spec_ID	UNIQUE_ID,
	     InformalGroupName	STRING,
	     Descrip	STRING );
CREATE TABLE CNST_CIP (
	     Constant_Spec_ID	UNIQUE_ID,
	     Package_ID	UNIQUE_ID );
CREATE TABLE CP_CPINP (
	     Id	UNIQUE_ID,
	     Parent_Package_ID	UNIQUE_ID );
CREATE TABLE CP_CP (
	     Package_ID	UNIQUE_ID,
	     ParentLink_Id	UNIQUE_ID,
	     Sys_ID	UNIQUE_ID,
	     Containing_Sys_ID	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING );
CREATE TABLE CL_IR (
	     Id	UNIQUE_ID,
	     Satisfaction_Element_Id	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING );
CREATE TABLE CL_IIR (
	     Id	UNIQUE_ID,
	     Ref_Id	UNIQUE_ID,
	     ImportedComp_Id	UNIQUE_ID,
	     Delegation_Id	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING );
CREATE TABLE CL_IPINS (
	     Satisfaction_Id	UNIQUE_ID,
	     ImportedProvision_Id	UNIQUE_ID );
CREATE TABLE CL_IP (
	     Id	UNIQUE_ID,
	     Name	STRING,
	     Descrip	STRING );
CREATE TABLE CL_IC (
	     Id	UNIQUE_ID,
	     AssignedComp_Id	UNIQUE_ID,
	     ParentComp_Id	UNIQUE_ID,
	     Component_Package_ID	UNIQUE_ID,
	     Mult	INTEGER,
	     ClassifierName	STRING,
	     Name	STRING,
	     Descrip	STRING );
CREATE TABLE CA_SMSME (
	     CPath_ID	UNIQUE_ID,
	     SMevt_ID	UNIQUE_ID );
CREATE TABLE CA_SMSMC (
	     CPath_ID	UNIQUE_ID,
	     OSM_ID	UNIQUE_ID,
	     DSM_ID	UNIQUE_ID,
	     OIObj_ID	UNIQUE_ID,
	     DIObj_ID	UNIQUE_ID );
CREATE TABLE CA_SMOAA (
	     APath_ID	UNIQUE_ID,
	     Attr_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID );
CREATE TABLE CA_SMOA (
	     APath_ID	UNIQUE_ID,
	     Obj_ID	UNIQUE_ID,
	     IObj_ID	UNIQUE_ID );
CREATE TABLE CA_SMEEE (
	     CPath_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID,
	     EEevt_ID	UNIQUE_ID );
CREATE TABLE CA_SMEED (
	     APath_ID	UNIQUE_ID,
	     EEdi_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID );
CREATE TABLE CA_SMEEC (
	     CPath_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID,
	     EEmod_ID	UNIQUE_ID );
CREATE TABLE CA_SMEEA (
	     APath_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID,
	     EEmod_ID	UNIQUE_ID );
CREATE TABLE CA_EESME (
	     CPath_ID	UNIQUE_ID,
	     SMevt_ID	UNIQUE_ID );
CREATE TABLE CA_EESMC (
	     CPath_ID	UNIQUE_ID,
	     EEmod_ID	UNIQUE_ID,
	     EE_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID );
CREATE TABLE CA_COMM (
	     CPath_ID	UNIQUE_ID,
	     SS_ID	UNIQUE_ID );
CREATE TABLE CA_ACC (
	     APath_ID	UNIQUE_ID,
	     SS_ID	UNIQUE_ID,
	     SM_ID	UNIQUE_ID,
	     IObj_ID	UNIQUE_ID );
CREATE TABLE R_SUBSUP (
	     Rel_ID	UNIQUE_ID );
CREATE TABLE R_SIMP (
	     Rel_ID	UNIQUE_ID );
CREATE TABLE R_RGO (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID );
CREATE TABLE R_RTO (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID,
	     Oid_ID	INTEGER );
CREATE TABLE R_ASSOC (
	     Rel_ID	UNIQUE_ID );
CREATE TABLE R_COMP (
	     Rel_ID	UNIQUE_ID,
	     Rel_Chn	STRING );
CREATE TABLE R_OIR (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID,
	     IObj_ID	UNIQUE_ID );
CREATE TABLE R_SUPER (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID );
CREATE TABLE R_SUB (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID );
CREATE TABLE R_PART (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID,
	     Mult	INTEGER,
	     Cond	INTEGER,
	     Txt_Phrs	STRING );
CREATE TABLE R_FORM (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID,
	     Mult	INTEGER,
	     Cond	INTEGER,
	     Txt_Phrs	STRING );
CREATE TABLE R_ASSR (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID,
	     Mult	INTEGER );
CREATE TABLE R_COTH (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID,
	     Mult	INTEGER,
	     Cond	INTEGER,
	     Txt_Phrs	STRING );
CREATE TABLE R_CONE (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID,
	     Mult	INTEGER,
	     Cond	INTEGER,
	     Txt_Phrs	STRING );
CREATE TABLE R_AOTH (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID,
	     Mult	INTEGER,
	     Cond	INTEGER,
	     Txt_Phrs	STRING );
CREATE TABLE R_AONE (
	     Obj_ID	UNIQUE_ID,
	     Rel_ID	UNIQUE_ID,
	     OIR_ID	UNIQUE_ID,
	     Mult	INTEGER,
	     Cond	INTEGER,
	     Txt_Phrs	STRING );
CREATE TABLE R_REL (
	     Rel_ID	UNIQUE_ID,
	     Numb	INTEGER,
	     Descrip	STRING,
	     SS_ID	UNIQUE_ID );

CREATE ROP REF_ID R3201 FROM MC 	S_AW 	( Sync_ID )
		         TO 1C  S_SYNC 	( Sync_ID );
CREATE ROP REF_ID R3200 FROM 1C 	S_AW 	( Brg_ID )
		         TO 1  	S_BRG 	( Brg_ID );
CREATE ROP REF_ID R117 FROM MC 	O_TPARM 	( Tfr_ID )
		         TO 1  	O_TFR 	( Tfr_ID );
CREATE ROP REF_ID R118 FROM MC 	O_TPARM 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R116 FROM MC 	O_TFR 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R115 FROM MC 	O_TFR 	( Obj_ID )
		         TO 1  	O_OBJ 	( Obj_ID );
CREATE ROP REF_ID R102 FROM MC 	O_ATTR 	( Obj_ID )
		         TO 1  	O_OBJ 	( Obj_ID );
CREATE ROP REF_ID R103 FROM 1C 	O_ATTR 	( PAttr_ID , Obj_ID )  PHRASE 'succeeds'
		         TO 1C  O_ATTR 	( Attr_ID , Obj_ID )  PHRASE 'precedes';
CREATE ROP REF_ID R114 FROM MC 	O_ATTR 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R106 FROM 1C 	O_BATTR 	( Attr_ID , Obj_ID )
		     TO 1  	O_ATTR 	( Attr_ID , Obj_ID );
CREATE ROP REF_ID R106 FROM 1C 	O_RATTR 	( Attr_ID , Obj_ID )
		     TO 1  	O_ATTR 	( Attr_ID , Obj_ID );
CREATE ROP REF_ID R113 FROM MC 	O_RATTR 	( BAttr_ID , BObj_ID )
		         TO 1  	O_BATTR 	( Attr_ID , Obj_ID );
CREATE ROP REF_ID R107 FROM 1C 	O_DBATTR 	( Attr_ID , Obj_ID )
		     TO 1  	O_BATTR 	( Attr_ID , Obj_ID );
CREATE ROP REF_ID R107 FROM 1C 	O_NBATTR 	( Attr_ID , Obj_ID )
		     TO 1  	O_BATTR 	( Attr_ID , Obj_ID );
CREATE ROP REF_ID R108 FROM M 	O_REF 	( Attr_ID , Obj_ID )
		         TO 1  	O_RATTR 	( Attr_ID , Obj_ID );
CREATE ROP REF_ID R112 FROM 1C 	O_REF 	( PARef_ID )  PHRASE 'succeeds'
		         TO 1C  O_REF 	( ARef_ID )  PHRASE 'precedes';
CREATE ROP REF_ID R105 FROM MC 	O_OIDA 	( Oid_ID , Obj_ID )
		         TO 1  	O_ID 	( Oid_ID , Obj_ID );
CREATE ROP REF_ID R105 FROM MC 	O_OIDA 	( Attr_ID , Obj_ID )
		         TO 1  	O_ATTR 	( Attr_ID , Obj_ID );
CREATE ROP REF_ID R104 FROM MC 	O_ID 	( Obj_ID )
		         TO 1  	O_OBJ 	( Obj_ID );
CREATE ROP REF_ID R101 FROM MC 	O_IOBJ 	( Obj_ID )
		         TO 1C  O_OBJ 	( Obj_ID );
CREATE ROP REF_ID R110 FROM M 	O_RTIDA 	( Oid_ID , OIR_ID , Obj_ID , Rel_ID )
		         TO 1  	R_RTO 	( Oid_ID , OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R110 FROM MC 	O_RTIDA 	( Attr_ID , Oid_ID , Obj_ID )
		         TO 1  	O_OIDA 	( Attr_ID , Oid_ID , Obj_ID );
CREATE ROP REF_ID R109 FROM MC 	R_RTO 	( Oid_ID , Obj_ID )
		         TO 1C  O_ID 	( Oid_ID , Obj_ID );
CREATE ROP REF_ID R111 FROM MC 	O_REF 	( OIR_ID , Obj_ID , Rel_ID )
		         TO 1  	R_RGO 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R111 FROM MC 	O_REF 	( RAttr_ID , ROIR_ID , ROid_ID , RObj_ID , Rel_ID )
		         TO 1  	O_RTIDA 	( Attr_ID , OIR_ID , Oid_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R120 FROM MC 	S_DIM 	( Attr_ID , Obj_ID )
		         TO 1C  O_ATTR 	( Attr_ID , Obj_ID );
CREATE ROP REF_ID R121 FROM MC 	S_DIM 	( TParm_ID )
		         TO 1C  O_TPARM 	( TParm_ID );
CREATE ROP REF_ID R122 FROM MC 	S_DIM 	( Tfr_ID )
		         TO 1C  O_TFR 	( Tfr_ID );
CREATE ROP REF_ID R123 FROM MC 	S_IRDT 	( Obj_ID )
		         TO 1  	O_OBJ 	( Obj_ID );
CREATE ROP REF_ID R124 FROM 1C 	O_TPARM 	( Previous_TParm_ID )  PHRASE 'succeeds'
		         TO 1C  O_TPARM 	( TParm_ID )  PHRASE 'precedes';
CREATE ROP REF_ID R125 FROM 1C 	O_TFR 	( Previous_Tfr_ID )  PHRASE 'succeeds'
		         TO 1C  O_TFR 	( Tfr_ID )  PHRASE 'precedes';
CREATE ROP REF_ID R502 FROM MC 	SM_EVT 	( SM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R501 FROM MC 	SM_STATE 	( SM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R504 FROM 1C 	SM_EIGN 	( SMspd_ID , SMevt_ID , SM_ID , SMstt_ID )
		     TO 1  	SM_SEME 	( SMspd_ID , SMevt_ID , SM_ID , SMstt_ID );
CREATE ROP REF_ID R504 FROM 1C 	SM_CH 	( SMspd_ID , SMevt_ID , SM_ID , SMstt_ID )
		     TO 1  	SM_SEME 	( SMspd_ID , SMevt_ID , SM_ID , SMstt_ID );
CREATE ROP REF_ID R504 FROM 1C 	SM_NSTXN 	( SMspd_ID , SMevt_ID , SM_ID , SMstt_ID )
		     TO 1  	SM_SEME 	( SMspd_ID , SMevt_ID , SM_ID , SMstt_ID );
CREATE ROP REF_ID R507 FROM 1C 	SM_NETXN 	( Trans_ID , SM_ID )
		     TO 1  	SM_TXN 	( Trans_ID , SM_ID );
CREATE ROP REF_ID R507 FROM 1C 	SM_CRTXN 	( Trans_ID , SM_ID )
		     TO 1  	SM_TXN 	( Trans_ID , SM_ID );
CREATE ROP REF_ID R507 FROM 1C 	SM_NSTXN 	( Trans_ID , SM_ID )
		     TO 1  	SM_TXN 	( Trans_ID , SM_ID );
CREATE ROP REF_ID R508 FROM MC 	SM_NETXN 	( SM_ID , SMstt_ID )
		         TO 1  	SM_STATE 	( SM_ID , SMstt_ID );
CREATE ROP REF_ID R506 FROM MC 	SM_TXN 	( SMspd_ID , SMstt_ID , SM_ID )
		         TO 1  	SM_STATE 	( SMspd_ID , SMstt_ID , SM_ID );
CREATE ROP REF_ID R505 FROM MC 	SM_TXN 	( SM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R510 FROM 1C 	SM_MEALY 	( SM_ID )
		     TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R510 FROM 1C 	SM_MOORE 	( SM_ID )
		     TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R511 FROM MC 	SM_MOAH 	( SM_ID )
		         TO 1  	SM_MOORE 	( SM_ID );
CREATE ROP REF_ID R511 FROM 1C 	SM_MOAH 	( SM_ID , SMstt_ID )
		         TO 1  	SM_STATE 	( SM_ID , SMstt_ID );
CREATE ROP REF_ID R512 FROM M 	SM_MEAH 	( SM_ID )
		         TO 1  	SM_MEALY 	( SM_ID );
CREATE ROP REF_ID R512 FROM 1C 	SM_MEAH 	( Trans_ID , SM_ID )
		         TO 1  	SM_TXN 	( Trans_ID , SM_ID );
CREATE ROP REF_ID R513 FROM 1C 	SM_MOAH 	( Act_ID , SM_ID )
		     TO 1  	SM_AH 	( Act_ID , SM_ID );
CREATE ROP REF_ID R513 FROM 1C 	SM_MEAH 	( Act_ID , SM_ID )
		     TO 1  	SM_AH 	( Act_ID , SM_ID );
CREATE ROP REF_ID R513 FROM 1C 	SM_TAH 	( Act_ID , SM_ID )
		     TO 1  	SM_AH 	( Act_ID , SM_ID );
CREATE ROP REF_ID R514 FROM 1  	SM_AH	( SM_ID , Act_ID )
		         TO 1  	SM_ACT 	( SM_ID , Act_ID );
CREATE ROP REF_ID R515 FROM MC 	SM_ACT 	( SM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R517 FROM 1C 	SM_ISM 	( SM_ID )
		     TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R517 FROM 1C 	SM_ASM 	( SM_ID )
		     TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R518 FROM 1C 	SM_ISM 	( Obj_ID )
		         TO 1  	O_OBJ 	( Obj_ID );
CREATE ROP REF_ID R519 FROM 1C 	SM_ASM 	( Obj_ID )
		         TO 1  	O_OBJ 	( Obj_ID );
CREATE ROP REF_ID R516 FROM MC 	SM_EVTDI 	( SM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R521 FROM MC 	SM_STATE 	( SMspd_ID , SM_ID )
		         TO 1C  SM_SUPDT 	( SMspd_ID , SM_ID );
CREATE ROP REF_ID R520 FROM M 	SM_EVT 	( SMspd_ID , SM_ID )
		         TO 1C  SM_SUPDT 	( SMspd_ID , SM_ID );
CREATE ROP REF_ID R522 FROM MC 	SM_SDI 	( SMspd_ID , SM_ID )
		         TO 1  	SM_SUPDT 	( SMspd_ID , SM_ID );
CREATE ROP REF_ID R522 FROM MC 	SM_SDI 	( SM_ID , SMedi_ID )
		         TO 1  	SM_EVTDI 	( SM_ID , SMedi_ID );
CREATE ROP REF_ID R523 FROM MC 	SM_SUPDT 	( SM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R524 FROM MC 	SM_EVTDI 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R525 FROM 1C 	SM_SEVT 	( SM_ID , SMevt_ID , SMspd_ID )
		     TO 1  	SM_EVT 	( SM_ID , SMevt_ID , SMspd_ID );
CREATE ROP REF_ID R525 FROM 1C 	SM_PEVT 	( SM_ID , SMevt_ID , SMspd_ID )
		     TO 1  	SM_EVT 	( SM_ID , SMevt_ID , SMspd_ID );
CREATE ROP REF_ID R503 FROM MC 	SM_SEME 	( SM_ID , SMstt_ID )
		         TO 1  	SM_STATE 	( SM_ID , SMstt_ID );
CREATE ROP REF_ID R503 FROM MC 	SM_SEME 	( SMevt_ID , SM_ID , SMspd_ID )
		         TO 1  	SM_SEVT 	( SMevt_ID , SM_ID , SMspd_ID );
CREATE ROP REF_ID R526 FROM 1C 	SM_NLEVT 	( SMevt_ID , SM_ID , SMspd_ID )
		     TO 1  	SM_SEVT 	( SMevt_ID , SM_ID , SMspd_ID );
CREATE ROP REF_ID R526 FROM 1C 	SM_LEVT 	( SMevt_ID , SM_ID , SMspd_ID )
		     TO 1  	SM_SEVT 	( SMevt_ID , SM_ID , SMspd_ID );
CREATE ROP REF_ID R526 FROM 1C 	SM_SGEVT 	( SMevt_ID , SM_ID , SMspd_ID )
		     TO 1  	SM_SEVT 	( SMevt_ID , SM_ID , SMspd_ID );
CREATE ROP REF_ID R509 FROM 1C 	SM_CRTXN 	( SM_ID , SMevt_ID )
		         TO 1C  SM_LEVT 	( SM_ID , SMevt_ID );
CREATE ROP REF_ID R527 FROM MC 	SM_NLEVT 	( polySM_ID , polySMevt_ID )
		         TO 1  	SM_PEVT 	( SM_ID , SMevt_ID );
CREATE ROP REF_ID R528 FROM 1C 	SM_SGEVT 	( Provided_Signal_Id )
		         TO 1C  SPR_PS 	( Id );
CREATE ROP REF_ID R529 FROM 1C 	SM_SGEVT 	( Required_Signal_Id )
		         TO 1C  SPR_RS 	( Id );
CREATE ROP REF_ID R530 FROM 1C 	SM_TAH 	( Trans_ID , SM_ID )
		         TO 1  	SM_TXN 	( Trans_ID , SM_ID );
CREATE ROP REF_ID R531 FROM MC 	S_DIM 	( SM_ID , SMedi_ID )
		         TO 1C  SM_EVTDI 	( SM_ID , SMedi_ID );
CREATE ROP REF_ID R532 FROM MC 	SM_EVTDI 	( SMevt_ID )
		         TO 1  	SM_EVT 	( SMevt_ID );
CREATE ROP REF_ID R533 FROM 1C 	SM_EVTDI 	( SM_ID , Previous_SMedi_ID )  PHRASE 'succeeds'
		         TO 1C  SM_EVTDI 	( SM_ID , SMedi_ID )  PHRASE 'precedes';
CREATE ROP REF_ID R9800 FROM MC 	SR_M 	( Result_Id )
		         TO 1  	SR_SR 	( Id );
CREATE ROP REF_ID R9801 FROM 1C 	SR_NM 	( Id )
		     TO 1  	SR_M 	( Id );
CREATE ROP REF_ID R9801 FROM 1C 	SR_CM 	( Id )
		     TO 1  	SR_M 	( Id );
CREATE ROP REF_ID R9802 FROM 1C 	SR_SR 	( MatchedParticipant_Id )
		         TO 1  	SP_SP 	( Id );
CREATE ROP REF_ID R9600 FROM 1C 	SQU_D 	( Id )
		     TO 1  	SQU_Q 	( Id );
CREATE ROP REF_ID R9600 FROM 1C 	SQU_R 	( Id )
		     TO 1  	SQU_Q 	( Id );
CREATE ROP REF_ID R9600 FROM 1C 	SQU_DE 	( Id )
		     TO 1  	SQU_Q 	( Id );
CREATE ROP REF_ID R9600 FROM 1C 	SQU_A 	( Id )
		     TO 1  	SQU_Q 	( Id );
CREATE ROP REF_ID R9700 FROM 1  	SP_SE	( Participant_Id )
		         TO 1  	SP_SP 	( Id );
CREATE ROP REF_ID R9702 FROM 1C 	SP_NS 	( Id )
		     TO 1  	SP_SE 	( Id );
CREATE ROP REF_ID R9702 FROM 1C 	SP_ALS 	( Id )
		     TO 1  	SP_SE 	( Id );
CREATE ROP REF_ID R9702 FROM 1C 	SP_DS 	( Id )
		     TO 1  	SP_SE 	( Id );
CREATE ROP REF_ID R9500 FROM 1  	SQU_Q	( Engine_Id )
		         TO 1C  SEN_E 	( Id );
CREATE ROP REF_ID R9501 FROM 1C 	SEN_ALE 	( Id )
		     TO 1  	SEN_E 	( Id );
CREATE ROP REF_ID R9501 FROM 1C 	SEN_DE 	( Id )
		     TO 1  	SEN_E 	( Id );
CREATE ROP REF_ID R9501 FROM 1C 	SEN_DCE 	( Id )
		     TO 1  	SEN_E 	( Id );
CREATE ROP REF_ID R9501 FROM 1C 	SEN_RE 	( Id )
		     TO 1  	SEN_E 	( Id );
CREATE ROP REF_ID R9502 FROM MC 	SP_SP 	( Engine_Id )
		         TO 1  	SEN_E 	( Id );
CREATE ROP REF_ID R9503 FROM MC 	SR_SR 	( Engine_Id )
		         TO 1  	SEN_E 	( Id );
CREATE ROP REF_ID R8000 FROM MC 	PE_PE 	( Package_ID )
		         TO 1C  EP_PKG 	( Package_ID );
CREATE ROP REF_ID R8001 FROM 1C 	S_DT 	( DT_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	SQ_P 	( Part_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	UC_UCA 	( Assoc_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	A_N 	( Id )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	O_OBJ 	( Obj_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	C_C 	( Id )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	CL_IC 	( Id )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	C_I 	( Id )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	EP_PKG 	( Package_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	CNST_CSP 	( Constant_Spec_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	A_AP 	( Id )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	A_E 	( Id )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	MSG_M 	( Msg_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	O_IOBJ 	( IObj_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	R_REL 	( Rel_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	S_EE 	( EE_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	S_SYNC 	( Sync_ID )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	C_SF 	( Id )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8001 FROM 1C 	C_DG 	( Id )
		     TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R8003 FROM MC 	PE_PE 	( Component_ID )
		         TO 1C  C_C 	( Id );
CREATE ROP REF_ID R9100 FROM MC 	G_EIS 	( Element_ID )
		         TO 1  	PE_PE 	( Element_ID );
CREATE ROP REF_ID R9100 FROM MC 	G_EIS 	( Sys_ID )
		         TO 1  	S_SYS 	( Sys_ID );
CREATE ROP REF_ID R1402 FROM 1C 	A_A 	( Package_ID )
		     TO 1  	EP_SPKG 	( Package_ID );
CREATE ROP REF_ID R1402 FROM 1C 	COMM_COMM 	( Package_ID )
		     TO 1  	EP_SPKG 	( Package_ID );
CREATE ROP REF_ID R1402 FROM 1C 	CP_CP 	( Package_ID )
		     TO 1  	EP_SPKG 	( Package_ID );
CREATE ROP REF_ID R1402 FROM 1C 	S_DPK 	( Package_ID )
		     TO 1  	EP_SPKG 	( Package_ID );
CREATE ROP REF_ID R1402 FROM 1C 	IP_IP 	( Package_ID )
		     TO 1  	EP_SPKG 	( Package_ID );
CREATE ROP REF_ID R1402 FROM 1C 	UC_UCC 	( Package_ID )
		     TO 1  	EP_SPKG 	( Package_ID );
CREATE ROP REF_ID R1402 FROM 1C 	SQ_S 	( Package_ID )
		     TO 1  	EP_SPKG 	( Package_ID );
CREATE ROP REF_ID R1401 FROM MC 	EP_PKG 	( Sys_ID )
		         TO 1C  S_SYS 	( Sys_ID );
CREATE ROP REF_ID R1400 FROM MC 	EP_SPKG 	( Container_Package_ID )
		         TO 1C  EP_PKG 	( Package_ID );
CREATE ROP REF_ID R1403 FROM MC 	EP_PIP 	( Parent_Package_ID )
		         TO 1  	EP_PKG 	( Package_ID );
CREATE ROP REF_ID R1404 FROM 1C 	EP_PIP 	( Child_Package_ID )
		         TO 1  	EP_PKG 	( Package_ID );
CREATE ROP REF_ID R1405 FROM MC 	EP_PKG 	( Direct_Sys_ID )
		         TO 1  	S_SYS 	( Sys_ID );
CREATE ROP REF_ID R1 FROM MC 	S_SS 	( Dom_ID )
		         TO 1  	S_DOM 	( Dom_ID );
CREATE ROP REF_ID R7 FROM MC 	S_EEM 	( SS_ID )
		         TO 1  	S_SS 	( SS_ID );
CREATE ROP REF_ID R9 FROM MC 	S_EEM 	( EE_ID )
		         TO 1  	S_EE 	( EE_ID );
CREATE ROP REF_ID R10 FROM MC 	S_EEEVT 	( EE_ID )
		         TO 1  	S_EE 	( EE_ID );
CREATE ROP REF_ID R12 FROM MC 	S_EEEDI 	( EE_ID )
		         TO 1  	S_EE 	( EE_ID );
CREATE ROP REF_ID R14 FROM MC 	S_DT 	( Dom_ID )
		         TO 1C  S_DOM 	( Dom_ID );
CREATE ROP REF_ID R16 FROM MC 	S_EEEDI 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R8 FROM MC 	S_EE 	( Dom_ID )
		         TO 1  	S_DOM 	( Dom_ID );
CREATE ROP REF_ID R17 FROM 1C 	S_CDT 	( DT_ID )
		     TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R17 FROM 1C 	S_UDT 	( DT_ID )
		     TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R17 FROM 1C 	S_EDT 	( DT_ID )
		     TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R17 FROM 1C 	S_SDT 	( DT_ID )
		     TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R17 FROM 1C 	S_IRDT 	( DT_ID )
		     TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R20 FROM MC 	S_BRG 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R21 FROM MC 	S_BPARM 	( Brg_ID )
		         TO 1  	S_BRG 	( Brg_ID );
CREATE ROP REF_ID R19 FROM MC 	S_BRG 	( EE_ID )
		         TO 1  	S_EE 	( EE_ID );
CREATE ROP REF_ID R15 FROM MC 	S_EEDI 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R22 FROM MC 	S_BPARM 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R11 FROM MC 	S_EEDI 	( EE_ID )
		         TO 1  	S_EE 	( EE_ID );
CREATE ROP REF_ID R13 FROM MC 	S_EEEDT 	( EEedi_ID , EE_ID )
		         TO 1  	S_EEEDI 	( EEedi_ID , EE_ID );
CREATE ROP REF_ID R13 FROM MC 	S_EEEDT 	( EEevt_ID , EE_ID )
		         TO 1  	S_EEEVT 	( EEevt_ID , EE_ID );
CREATE ROP REF_ID R2 FROM MC 	O_OBJ 	( SS_ID )
		         TO 1C  S_SS 	( SS_ID );
CREATE ROP REF_ID R4 FROM MC 	R_REL 	( SS_ID )
		         TO 1C  S_SS 	( SS_ID );
CREATE ROP REF_ID R5 FROM MC 	CA_COMM 	( SS_ID )
		         TO 1  	S_SS 	( SS_ID );
CREATE ROP REF_ID R6 FROM MC 	CA_ACC 	( SS_ID )
		         TO 1  	S_SS 	( SS_ID );
CREATE ROP REF_ID R3 FROM MC 	O_IOBJ 	( SS_ID )
		         TO 1  	S_SS 	( SS_ID );
CREATE ROP REF_ID R27 FROM MC 	S_ENUM 	( EDT_DT_ID )
		         TO 1  	S_EDT 	( DT_ID );
CREATE ROP REF_ID R23 FROM MC 	S_SYNC 	( Dom_ID )
		         TO 1  	S_DOM 	( Dom_ID );
CREATE ROP REF_ID R25 FROM MC 	S_SYNC 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R24 FROM MC 	S_SPARM 	( Sync_ID )
		         TO 1  	S_SYNC 	( Sync_ID );
CREATE ROP REF_ID R26 FROM MC 	S_SPARM 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R28 FROM MC 	S_DOM 	( Sys_ID )
		         TO 1C  S_SYS 	( Sys_ID );
CREATE ROP REF_ID R29 FROM MC 	S_FPK 	( Dom_ID )
		         TO 1C  S_DOM 	( Dom_ID );
CREATE ROP REF_ID R31 FROM MC 	S_FIP 	( FunPack_ID )
		         TO 1  	S_FPK 	( FunPack_ID );
CREATE ROP REF_ID R31 FROM 1  	S_FIP 	( Sync_ID )
		         TO 1  	S_SYNC 	( Sync_ID );
CREATE ROP REF_ID R30 FROM 1C 	S_FPIP 	( FunPack_ID )
		         TO 1  	S_FPK 	( FunPack_ID );
CREATE ROP REF_ID R32 FROM MC 	S_FPK 	( Parent_FunPack_ID )
		         TO 1C  S_FPIP 	( FunPack_ID );
CREATE ROP REF_ID R33 FROM MC 	S_EEIP 	( EEPack_ID )
		         TO 1  	S_EEPK 	( EEPack_ID );
CREATE ROP REF_ID R33 FROM 1  	S_EEIP 	( EE_ID )
		         TO 1  	S_EE 	( EE_ID );
CREATE ROP REF_ID R34 FROM 1C 	S_EEPIP 	( EEPack_ID )
		         TO 1  	S_EEPK 	( EEPack_ID );
CREATE ROP REF_ID R35 FROM MC 	S_EEPK 	( Parent_EEPack_ID )
		         TO 1C  S_EEPIP 	( EEPack_ID );
CREATE ROP REF_ID R36 FROM MC 	S_EEPK 	( Dom_ID )
		         TO 1C  S_DOM 	( Dom_ID );
CREATE ROP REF_ID R37 FROM 1C 	S_DPIP 	( Package_ID )
		         TO 1  	S_DPK 	( Package_ID );
CREATE ROP REF_ID R38 FROM MC 	S_DPK 	( Parent_Package_ID )
		         TO 1C  S_DPIP 	( Package_ID );
CREATE ROP REF_ID R39 FROM 1C 	S_DIP 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R39 FROM MC 	S_DIP 	( Package_ID )
		         TO 1  	S_DPK 	( Package_ID );
CREATE ROP REF_ID R40 FROM MC 	S_DPK 	( Dom_ID )
		         TO 1C  S_DOM 	( Dom_ID );
CREATE ROP REF_ID R42 FROM 1C 	S_SIS 	( Child_SS_ID )
		         TO 1  	S_SS 	( SS_ID );
CREATE ROP REF_ID R41 FROM MC 	S_SIS 	( Parent_SS_ID )
		         TO 1  	S_SS 	( SS_ID );
CREATE ROP REF_ID R43 FROM 1C 	S_SID 	( SS_ID )
		         TO 1  	S_SS 	( SS_ID );
CREATE ROP REF_ID R43 FROM MC 	S_SID 	( Dom_ID )
		         TO 1  	S_DOM 	( Dom_ID );
CREATE ROP REF_ID R44 FROM MC 	S_MBR 	( Parent_DT_DT_ID )
		         TO 1  	S_SDT 	( DT_ID );
CREATE ROP REF_ID R45 FROM MC 	S_MBR 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R46 FROM 1C 	S_MBR 	( Previous_Member_ID , Parent_DT_DT_ID )  PHRASE 'succeeds'
		         TO 1C  S_MBR 	( Member_ID , Parent_DT_DT_ID )  PHRASE 'precedes';
CREATE ROP REF_ID R47 FROM MC 	S_DIS 	( Dom_ID )
		         TO 1  	S_DOM 	( Dom_ID );
CREATE ROP REF_ID R47 FROM MC 	S_DIS 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R49 FROM MC 	S_DIM 	( BParm_ID )
		         TO 1C  S_BPARM 	( BParm_ID );
CREATE ROP REF_ID R50 FROM MC 	S_DIM 	( Brg_ID )
		         TO 1C  S_BRG 	( Brg_ID );
CREATE ROP REF_ID R51 FROM MC 	S_DIM 	( Sync_ID )
		         TO 1C  S_SYNC 	( Sync_ID );
CREATE ROP REF_ID R52 FROM MC 	S_DIM 	( SParm_ID )
		         TO 1C  S_SPARM 	( SParm_ID );
CREATE ROP REF_ID R53 FROM MC 	S_DIM 	( Member_ID , DT_ID )
		         TO 1C  S_MBR 	( Member_ID , Parent_DT_DT_ID );
CREATE ROP REF_ID R54 FROM 1C 	S_SPARM 	( Previous_SParm_ID )  PHRASE 'succeeds'
		         TO 1C  S_SPARM 	( SParm_ID )  PHRASE 'precedes';
CREATE ROP REF_ID R55 FROM 1C 	S_BPARM 	( Previous_BParm_ID )  PHRASE 'succeeds'
		         TO 1C  S_BPARM 	( BParm_ID )  PHRASE 'precedes';
CREATE ROP REF_ID R56 FROM 1C 	S_ENUM 	( Previous_Enum_ID )  PHRASE 'succeeds'
		         TO 1C  S_ENUM 	( Enum_ID )  PHRASE 'precedes';
CREATE ROP REF_ID R18 FROM MC 	S_UDT 	( CDT_DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R1500 FROM MC 	CNST_SYC 	( DT_ID )
		         TO 1  	S_DT 	( DT_ID );
CREATE ROP REF_ID R1502 FROM 1C 	CNST_LFSC 	( Const_ID , DT_ID )
		     TO 1  	CNST_SYC 	( Const_ID , DT_ID );
CREATE ROP REF_ID R1503 FROM 1C 	CNST_LSC 	( Const_ID , DT_ID )
		     TO 1  	CNST_LFSC 	( Const_ID , DT_ID );
CREATE ROP REF_ID R1504 FROM MC 	CNST_SYC 	( Constant_Spec_ID )
		         TO 1  	CNST_CSP 	( Constant_Spec_ID );
CREATE ROP REF_ID R1505 FROM 1C 	CNST_SYC 	( Previous_Const_ID , Previous_DT_DT_ID )  PHRASE 'succeeds'
		         TO 1C  CNST_SYC 	( Const_ID , DT_ID )  PHRASE 'precedes';
CREATE ROP REF_ID R1506 FROM 1  	CNST_CIP 	( Constant_Spec_ID )
		         TO 1  	CNST_CSP 	( Constant_Spec_ID );
CREATE ROP REF_ID R1506 FROM MC 	CNST_CIP 	( Package_ID )
		         TO 1  	S_DPK 	( Package_ID );
CREATE ROP REF_ID R4600 FROM MC 	CP_CPINP 	( Parent_Package_ID )
		         TO 1  	CP_CP 	( Package_ID );
CREATE ROP REF_ID R4601 FROM 1  	CP_CP	( ParentLink_Id )
		         TO 1C  CP_CPINP 	( Id );
CREATE ROP REF_ID R4602 FROM MC 	CP_CP 	( Sys_ID )
		         TO 1C  S_SYS 	( Sys_ID );
CREATE ROP REF_ID R4604 FROM MC 	C_C 	( Package_ID )
		         TO 1C  CP_CP 	( Package_ID );
CREATE ROP REF_ID R4606 FROM MC 	CP_CP 	( Containing_Sys_ID )
		         TO 1  	S_SYS 	( Sys_ID );
CREATE ROP REF_ID R4607 FROM MC 	IP_IP 	( Component_Package_ID )
		         TO 1C  CP_CP 	( Package_ID );
CREATE ROP REF_ID R4605 FROM MC 	CL_IC 	( Component_Package_ID )
		         TO 1C  CP_CP 	( Package_ID );
CREATE ROP REF_ID R4608 FROM MC 	C_C 	( Root_Package_ID )
		         TO 1C  CP_CP 	( Package_ID );
CREATE ROP REF_ID R4700 FROM MC 	CL_IIR 	( ImportedComp_Id )
		         TO 1  	CL_IC 	( Id );
CREATE ROP REF_ID R4701 FROM MC 	CL_IIR 	( Ref_Id )
		         TO 1C  C_IR 	( Id );
CREATE ROP REF_ID R4703 FROM 1C 	CL_IP 	( Id )
		     TO 1  	CL_IIR 	( Id );
CREATE ROP REF_ID R4703 FROM 1C 	CL_IR 	( Id )
		     TO 1  	CL_IIR 	( Id );
CREATE ROP REF_ID R4704 FROM 1C 	CL_IIR 	( Delegation_Id )
		         TO 1C  C_DG 	( Id );
CREATE ROP REF_ID R4705 FROM 1C 	CL_IPINS 	( Satisfaction_Id )
		         TO 1  	C_SF 	( Id );
CREATE ROP REF_ID R4705 FROM MC 	CL_IPINS 	( ImportedProvision_Id )
		         TO 1  	CL_IP 	( Id );
CREATE ROP REF_ID R4706 FROM 1C 	CL_IR 	( Satisfaction_Element_Id )
		         TO 1C  C_SF 	( Id );
CREATE ROP REF_ID R401 FROM 1C 	CA_EESMC 	( CPath_ID )
		     TO 1  	CA_COMM 	( CPath_ID );
CREATE ROP REF_ID R401 FROM 1C 	CA_SMEEC 	( CPath_ID )
		     TO 1  	CA_COMM 	( CPath_ID );
CREATE ROP REF_ID R401 FROM 1C 	CA_SMSMC 	( CPath_ID )
		     TO 1  	CA_COMM 	( CPath_ID );
CREATE ROP REF_ID R404 FROM MC 	CA_EESME 	( CPath_ID )
		         TO 1  	CA_EESMC 	( CPath_ID );
CREATE ROP REF_ID R408 FROM MC 	CA_SMSME 	( CPath_ID )
		         TO 1  	CA_SMSMC 	( CPath_ID );
CREATE ROP REF_ID R412 FROM MC 	CA_SMEEE 	( CPath_ID )
		         TO 1  	CA_SMEEC 	( CPath_ID );
CREATE ROP REF_ID R413 FROM MC 	CA_SMEEE 	( EEevt_ID , EE_ID )
		         TO 1  	S_EEEVT 	( EEevt_ID , EE_ID );
CREATE ROP REF_ID R414 FROM MC 	CA_SMSMC 	( DIObj_ID )
		         TO 1C  O_IOBJ 	( IObj_ID );
CREATE ROP REF_ID R415 FROM 1C 	CA_SMOA 	( APath_ID )
		     TO 1  	CA_ACC 	( APath_ID );
CREATE ROP REF_ID R415 FROM 1C 	CA_SMEEA 	( APath_ID )
		     TO 1  	CA_ACC 	( APath_ID );
CREATE ROP REF_ID R417 FROM MC 	CA_SMOA 	( Obj_ID )
		         TO 1  	O_OBJ 	( Obj_ID );
CREATE ROP REF_ID R418 FROM MC 	CA_SMOAA 	( APath_ID , Obj_ID )
		         TO 1  	CA_SMOA 	( APath_ID , Obj_ID );
CREATE ROP REF_ID R419 FROM MC 	CA_SMOAA 	( Attr_ID , Obj_ID )
		         TO 1  	O_ATTR 	( Attr_ID , Obj_ID );
CREATE ROP REF_ID R420 FROM MC 	CA_SMOA 	( IObj_ID )
		         TO 1C  O_IOBJ 	( IObj_ID );
CREATE ROP REF_ID R421 FROM MC 	CA_SMEEA 	( EEmod_ID , EE_ID )
		         TO 1  	S_EEM 	( EEmod_ID , EE_ID );
CREATE ROP REF_ID R422 FROM MC 	CA_SMEED 	( APath_ID , EE_ID )
		         TO 1  	CA_SMEEA 	( APath_ID , EE_ID );
CREATE ROP REF_ID R423 FROM MC 	CA_SMEED 	( EEdi_ID , EE_ID )
		         TO 1  	S_EEDI 	( EEdi_ID , EE_ID );
CREATE ROP REF_ID R424 FROM MC 	CA_SMSMC 	( OIObj_ID )
		         TO 1C  O_IOBJ 	( IObj_ID );
CREATE ROP REF_ID R425 FROM MC 	CA_ACC 	( IObj_ID )
		         TO 1C  O_IOBJ 	( IObj_ID );
CREATE ROP REF_ID R405 FROM MC 	CA_EESME 	( SMevt_ID )
		         TO 1  	SM_EVT 	( SMevt_ID );
CREATE ROP REF_ID R409 FROM MC 	CA_SMSME 	( SMevt_ID )
		         TO 1  	SM_EVT 	( SMevt_ID );
CREATE ROP REF_ID R403 FROM MC 	CA_EESMC 	( SM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R402 FROM MC 	CA_EESMC 	( EEmod_ID , EE_ID )
		         TO 1  	S_EEM 	( EEmod_ID , EE_ID );
CREATE ROP REF_ID R410 FROM MC 	CA_SMEEC 	( SM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R411 FROM MC 	CA_SMEEC 	( EEmod_ID , EE_ID )
		         TO 1  	S_EEM 	( EEmod_ID , EE_ID );
CREATE ROP REF_ID R406 FROM MC 	CA_SMSMC 	( OSM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R407 FROM MC 	CA_SMSMC 	( DSM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R416 FROM MC 	CA_ACC 	( SM_ID )
		         TO 1  	SM_SM 	( SM_ID );
CREATE ROP REF_ID R201 FROM M 	R_OIR 	( Rel_ID )
		         TO 1  	R_REL 	( Rel_ID );
CREATE ROP REF_ID R201 FROM MC 	R_OIR 	( Obj_ID )
		         TO 1  	O_OBJ 	( Obj_ID );
CREATE ROP REF_ID R206 FROM 1C 	R_SIMP 	( Rel_ID )
		     TO 1  	R_REL 	( Rel_ID );
CREATE ROP REF_ID R206 FROM 1C 	R_COMP 	( Rel_ID )
		     TO 1  	R_REL 	( Rel_ID );
CREATE ROP REF_ID R206 FROM 1C 	R_ASSOC 	( Rel_ID )
		     TO 1  	R_REL 	( Rel_ID );
CREATE ROP REF_ID R206 FROM 1C 	R_SUBSUP 	( Rel_ID )
		     TO 1  	R_REL 	( Rel_ID );
CREATE ROP REF_ID R207 FROM M 	R_PART 	( Rel_ID )
		         TO 1  	R_SIMP 	( Rel_ID );
CREATE ROP REF_ID R208 FROM 1C 	R_FORM 	( Rel_ID )
		         TO 1  	R_SIMP 	( Rel_ID );
CREATE ROP REF_ID R209 FROM 1  	R_AONE	( Rel_ID )
		         TO 1  	R_ASSOC 	( Rel_ID );
CREATE ROP REF_ID R210 FROM 1  	R_AOTH	( Rel_ID )
		         TO 1  	R_ASSOC 	( Rel_ID );
CREATE ROP REF_ID R211 FROM 1  	R_ASSR	( Rel_ID )
		         TO 1  	R_ASSOC 	( Rel_ID );
CREATE ROP REF_ID R212 FROM 1  	R_SUPER	( Rel_ID )
		         TO 1  	R_SUBSUP 	( Rel_ID );
CREATE ROP REF_ID R213 FROM MC 	R_SUB 	( Rel_ID )
		         TO 1  	R_SUBSUP 	( Rel_ID );
CREATE ROP REF_ID R214 FROM 1  	R_CONE	( Rel_ID )
		         TO 1  	R_COMP 	( Rel_ID );
CREATE ROP REF_ID R215 FROM 1  	R_COTH	( Rel_ID )
		         TO 1  	R_COMP 	( Rel_ID );
CREATE ROP REF_ID R203 FROM 1C 	R_RTO 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_OIR 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R203 FROM 1C 	R_RGO 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_OIR 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R203 FROM 1C 	R_CONE 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_OIR 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R203 FROM 1C 	R_COTH 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_OIR 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R205 FROM 1C 	R_SUB 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_RGO 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R205 FROM 1C 	R_FORM 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_RGO 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R205 FROM 1C 	R_ASSR 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_RGO 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R204 FROM 1C 	R_SUPER 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_RTO 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R204 FROM 1C 	R_PART 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_RTO 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R204 FROM 1C 	R_AONE 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_RTO 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R204 FROM 1C 	R_AOTH 	( OIR_ID , Obj_ID , Rel_ID )
		     TO 1  	R_RTO 	( OIR_ID , Obj_ID , Rel_ID );
CREATE ROP REF_ID R202 FROM MC 	R_OIR 	( IObj_ID )
		         TO 1C  O_IOBJ 	( IObj_ID );

