//======================================================================
//
// File: com/mentor/nucleus/bp/core/inspector/MessageArgumentTreeDifferenceSlot.java
//
// WARNING:      Do not edit this generated file
// Generated by: arc/create_model_inspector.arc
// Version:      $Revision$
//
// (c) Copyright 2004-2014 by Mentor Graphics Corp.  All rights reserved.
//
//======================================================================
package com.mentor.nucleus.bp.core.inspector;

import com.mentor.nucleus.bp.core.*;

public class MessageArgumentTreeDifferenceSlot {

	public MessageArgumentTreeDifferenceSlot() {
	}

	/**
	 * Returns a "slot number" to be used when comparing and merging tree elements
	 * that contain multiple children.  All model element inspector's contain this 
	 * function, but it only returns a value for cases where it a parent element
	 * in a tree and the parent has multiple children.
	 * 
	 * @returns 0 if this is not a "parent" in the tree OR if the parent has less 
	 * than 2 children. 
	 */
	public int getTreeDifferenceSlot(Object element) {
		if (element instanceof BridgeParameter_c) {
			return 1;
		}
		if (element instanceof OperationParameter_c) {
			return 2;
		}
		if (element instanceof FunctionParameter_c) {
			return 3;
		}
		if (element instanceof StateMachineEventDataItem_c) {
			return 4;
		}
		if (element instanceof PropertyParameter_c) {
			return 5;
		}
		if (element instanceof InformalArgument_c) {
			return 6;
		}
		return 0;
	}

}
