--========================================================================
--
-- File: metamodel_schema.sql
--
-- WARNING:      Do not edit this generated file
-- Generated by: ../../MC-Java/schema_gen.arc
-- Version:      $Revision: 1.17 $
--
--(c) Copyright 2005-2014 by Mentor Graphics Corp. All rights reserved.
--
--========================================================================
-- Licensed under the Apache License, Version 2.0 (the "License"); you may not
-- use this file except in compliance with the License.  You may obtain a copy
-- of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
-- WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   See the
-- License for the specific language governing permissions and limitations under
-- the License.
--======================================================================== 
--

CREATE TABLE CST_STT (
	     sttID	INTEGER );
CREATE TABLE CST_STR (
	     sttID	INTEGER );
CREATE TABLE CST_STL (
	     sttID	INTEGER );
CREATE TABLE CST_SPT (
	     sptID	INTEGER );
CREATE TABLE CST_SFT (
	     sftID	INTEGER,
	     sptID	INTEGER );
CREATE TABLE CST_LT (
	     llsID	INTEGER,
	     lrsID	INTEGER );
CREATE TABLE CST_LRS (
	     lrsID	INTEGER );
CREATE TABLE CST_LLS (
	     llsID	INTEGER );
CREATE TABLE CST_IDT (
	     primaryID	INTEGER,
	     secondaryID	INTEGER,
	     tertiaryID	INTEGER );

CREATE ROP REF_ID R1 FROM 1  	CST_SFT	( sptID )
		         TO 1  	CST_SPT 	( sptID );
CREATE ROP REF_ID R2 FROM 1  	CST_LT 	( llsID )
		         TO 1  	CST_LLS 	( llsID );
CREATE ROP REF_ID R2 FROM 1  	CST_LT 	( lrsID )
		         TO 1  	CST_LRS 	( lrsID );
CREATE ROP REF_ID R3 FROM 1C 	CST_STL 	( sttID )
		     TO 1  	CST_STT 	( sttID );
CREATE ROP REF_ID R3 FROM 1C 	CST_STR 	( sttID )
		     TO 1  	CST_STT 	( sttID );

